### ISSUE TITLE
Типизация кода. Подсвечивать ошибки от strict-types другим цветом

### ISSUE THREAD

**Issue by Stepa86** [1C-Company/v8-code-style#1003]
### Описание проблемы

Ошибки в редакторе выглядят одинаково - и реальные ошибки в коде, которые точно приведут к падению в рантайме и ошибки приведения типов (ложноположительные в большинстве случаев из-за разных причин).

Это приводит к тому, что забытую точку с запятой просто не видно - весь код становится красным, а истинную причину найти получается только в рантайме.

При разработке без типизирования можно добавить новый параметр у локального метода и сразу увидеть упавшие вызовы. При типизировании так не получается.

### Описание решения проблемы

Отрисовывать ошибки типизации с другим типом, цветом и пиктограммой. Например, фиолетовым, а в иконке сделать "_t_"

**Comment by marmyshev** [comment]
Вообще, странный посыл: «модуль красный, но при этом хватает ума запускать отладку»… вместо того чтобы искать и исправлять ошибку в коде до запуска отладки.

 То есть совсем непонятно, зачем в таком случае строгая типизация в модуле если хочется необращать на неё внимание? 😁 если модуль написан так что типизация не может быть адекватной - просто отключайте строгую типизацию, ну она ведь уже не строгая?

Возможность сменить цвет есть: красный, желтый, синий (или серый? Не помню точно) - понизив уровень критичности всех проверок группы в настройках проекта.  Это оно?

Прошу уточнить.

Хочется, чтобы ошибки были критичными, но не такими критичными как другие критичные? 

И цвет ошибок ещё какой-то «критичный но не очень»? Это тогда пожелание к самой ЕДТ и редактору модуля… (щас 3 цвета)

**Comment by Stepa86** [comment]
Был модуль "белый", без ошибок, все хорошо оттипизировано. Делаешь ошибку которая ломает парсер комментариев на тип. Весь модуль красный - причину не найти. Или он сам ломается на ровном месте.

И как рефакторить старые модули? Добавил типизацию, поправил, что поправилось, погрустил, где не поправилось (оно вон на ОткрытьФорму стало ругаться) и отключаешь типизацию, чтоб можно было видеть и другие ошибки?

Я вообще не понимаю почему критичность у ошибок типизации такая же, как при нарушении синтаксиса, когда модуль тупо не откроется в рантайме и выше, чем вызов несуществующего метода в другом модуле.

Но по тону я понял, что у вас все хорошо, а мы тут, обычные 1Сники, просто не умеем пользоваться вашим великим творением. Извините за доставленные неудобства

**Comment by marmyshev** [comment]
Как-то обидно написано.

Проект открытый - присылайте ваши доработки по вашему пожеланию через PR.

**Comment by marmyshev** [comment]
> Был модуль "белый", без ошибок, все хорошо оттипизировано. Делаешь ошибку которая ломает парсер комментариев на тип. Весь модуль красный - причину не найти. 

В этом сценарии не понятно, как  сломав док.коммент в текущей вот сроке в редакторе (мгновенно, вот прям сейчас) - не возможно найти причину слома? 
Звучит, как-будто "ломатель" модуля и "искатель" причины слома - это разные люди, или в разных инструментах работаю или еще что-то.

**Comment by marmyshev** [comment]
> И как рефакторить старые модули? Добавил типизацию, поправил, что поправилось, погрустил, где не поправилось (оно вон на ОткрытьФорму стало ругаться) и отключаешь типизацию, чтоб можно было видеть и другие ошибки?

Да, тут так - либо модуль полностью строго-типизирован, либо нет. Включил - поправил что возможно, если не возможно доправить до конца - выключил.

**Comment by marmyshev** [comment]
> Я вообще не понимаю почему критичность у ошибок типизации такая же, как при нарушении синтаксиса, когда модуль тупо не откроется в рантайме и выше, чем вызов несуществующего метода в другом модуле.

Да, в планах сделать "строгую типизацию" еще строже - чтобы даже отладку невозможно было запустить или изменения в базу залить.
В основном, жалуются как раз на то, что типизация недостаточно строгая...
