### ISSUE TITLE
Опечатки в настройке параметров проекта (2021.3.2, 0.2.0.159)

### ISSUE THREAD

**Issue by NikitaMikhaylovSB** [1C-Company/v8-code-style#1005]
### Описание ошибки

В настройках проекта содержаться опечатки, см. приложенный скриншот

### Как воспроизвести

Откройте настройки проекта, убедитесь в наличии опечаток

### Скриншоты

![изображение](https://user-images.githubusercontent.com/37539066/157311215-41ad1386-5d67-4263-bbf8-e88a99a2e438.png)

### Ожидаемое поведение

Не должно быть опечаток 

### Лог рабочей области

(не требуется)

### Версия 1С:Code style V8

0.2.0.159

### Версия 1С:EDT

2021.3.2

### Операционная система

Windows

**Comment by marmyshev** [comment]
Опечатки тут

https://github.com/1C-Company/v8-code-style/blob/master/bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/internal/messages_ru.properties#L15

https://github.com/1C-Company/v8-code-style/blob/master/bundles/com.e1c.v8codestyle.autosort/src/com/e1c/v8codestyle/internal/autosort/messages_ru.properties#L16
