### ISSUE TITLE
Форматирование модуля формы приводит к удалению всех пробелов между "Асинх Процедура" и "Асинх Функция"

### ISSUE THREAD

**Issue by motivix** [1C-Company/v8-code-style#1006]
### Описание ошибки

Ошибка в том, что Форматирование модуля приводит к удалению всех пробелов МЕЖДУ наименование процедуры или функции И "Асинх Процедура" или "Асинх Функция".
Это делает модули неработоспособными.

### Как воспроизвести

1. Открыть все модули всех форм и все общие модули работающие на клиенте конфигурации
2. Отформатировать стандартной функцией форматирования нажатием комбинацией клавиш Ctrl+Shift+F
3. Закрыть и сохранить все модули
4. Обновить разрабатываемые приложения нажав комбинацию Shift+F7
5. В результате конфигурация не дееспособна и вам потребуется не мало усилий, чтобы восстановить все модули

### Скриншоты

![image](https://user-images.githubusercontent.com/62136047/157474624-7dc79262-e553-4ff2-8369-2cb749d92f43.png)
![image](https://user-images.githubusercontent.com/62136047/157474724-62c897b8-d811-4498-8c42-52c3534501f8.png)

### Ожидаемое поведение

 Форматирование модуля приводит к удалению ТОЛЬКО ЛИШНИХ ПРОБЕЛОВ между наименование процедуры или функции И "Асинх Процедура" или "Асинх Функция", что делает модули неработоспособными.

### Лог рабочей области

[trace.log](https://github.com/1C-Company/1c-edt-issues/files/8215995/trace.log)
[ — копия.log](https://github.com/1C-Company/1c-edt-issues/files/8216001/default.log)

### Версия 1С:Code style V8

0.2.0

### Версия 1С:EDT

Ruby 2021.3.2.7

### Дополнительная информация

Проблема повторяется и в предыдущих версиях EDT

**Comment by marmyshev** [comment]
К плагину "Стандартов разработки" это не имеет отношения.

https://github.com/1C-Company/1c-edt-issues/issues/398
