### ISSUE TITLE
Ложное срабатывание проверки: invocation-parameter-type-intersect

### ISSUE THREAD

**Issue by goodwinvu** [1C-Company/v8-code-style#1039]
## Название/код проверки

Код проверки: `invocation-parameter-type-intersect`

Версия плагина: `0.6.0.101`

## Пример кода/метаданных содержащих ошибку

```bsl
	РезультатСхема = Новый СхемаЗапроса;
	
	ЗапросВыбора = РезультатСхема.ПакетЗапросов[0];
	
	ОператорВыбора = ЗапросВыбора.Операторы[0];
	Источник1 = ОператорВыбора.Источники.Добавить("Справочник.ДоговорыКонтрагентов", "Договоры");
	Источник2 = ОператорВыбора.Источники.Добавить("Справочник.Контрагенты", "Контрагенты");
```

![image](https://user-images.githubusercontent.com/32670094/173009389-8acce1da-66a4-4730-a8e9-6f932ce59bd9.png)

## Почему это НЕ ошибка

Согласно описанию ИсточникиСхемыЗапроса первый параметры может быть строкой - именем :

ИсточникиСхемыЗапроса.Добавить (QuerySchemaSources.Add)

ИсточникиСхемыЗапроса (QuerySchemaSources)

Добавить (Add)

Доступен, начиная с версии 8.3.5.

Вариант синтаксиса: Добавить таблицу схемы запроса

Синтаксис:
Добавить(<ДоступнаяТаблица>, <Псевдоним>)
Параметры:

<ДоступнаяТаблица> (обязательный)
Тип: [Строка](http://127.0.0.1:53242/help/topic/com._1c.g5.v8.dt.platform.doc_v8_3_21/html/SyntaxHelperLanguage/def_String), [ДоступнаяТаблицаСхемыЗапроса](http://127.0.0.1:53242/help/topic/com._1c.g5.v8.dt.platform.doc_v8_3_21/html/SyntaxHelperContext/objects/catalog213/catalog2171/QuerySchemaAvailableTable.html), [ДоступнаяВложеннаяТаблицаСхемыЗапроса](http://127.0.0.1:53242/help/topic/com._1c.g5.v8.dt.platform.doc_v8_3_21/html/SyntaxHelperContext/objects/catalog213/catalog2171/QuerySchemaAvailableNestedTable.html). 
Имя таблицы, доступная таблица или доступная вложенная таблица, полученные из доступных таблиц схемы запроса.
Если передано имя таблицы, и по нему не удалось найти таблицу, то будет сгенерировано исключение.

<Псевдоним> (необязательный)
Тип: [Строка](http://127.0.0.1:53242/help/topic/com._1c.g5.v8.dt.platform.doc_v8_3_21/html/SyntaxHelperLanguage/def_String). 
Псевдоним добавляемого источника. Если не указан, то псевдоним добавляемого источника сгенерируется автоматически. Если параметр задан, сначала будет выполнена проверка корректности псевдонима. Если указан недопустимый псевдоним, генерируется исключение, содержащее описание ошибки.

## Дополнительные материалы

- [Ссылка на стандарт на сайте ИТС](https://its.1c.ru/...)

**Comment by marmyshev** [comment]
Дубль #992
