### ISSUE TITLE
Добавить проверку, что состав структуры не меняется вне функции-конструктора

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/v8-code-style#1054]
### Описание проблемы

Есть функция-конструктор для структуры, однако программисты меняют состав структуры методами Вставить Удалить, что приводит к определенным ошибкам из-за неопределенности состава данных.

### Описание решения проблемы

Есть предложение: для структур **в строгих типах** запретить методы "Вставить", "Удалить" в функциях и процедурах, где она не объявляется (разрешить только в функциях-конструкторах). Метод Удалить для структуры можно просто объявить "незаконным".

### Дополнительная информация

т.е. просто ищем 
`ИмяСтруктуры = Новый Структура`
Если конструкции нет в текущей процедуре / функции - запрет на модификацию

**Comment by RedMammoth** [comment]
Думаю также стоить продумать, есть ли случаи, когда данное поведение можно разрешить без подавления. Например, я хочу сделать в структурах "наследование" расширением свойств базовой структуры, а не композицию с включением базовой структуры как вложенную.
Например, я делаю интеграцию в разные формы, мне нужно определить параметры, которые должны быть переданы в процедуру интегратор из события формы ПриСозданииНаСервере. Но для разных форм (списка и объекта) параметры немного отличаются и я хочу:
- создать базовый конструктор с общими свойствами и спрятать его в СПФ (в АПИ эта структура не нужна)
- затем в ПИ создать две функции конструктор для "наследников" ПараметрыДляФормыСписка, ПараметрыДляФормыОбъекта, в реализации я вызываю базовый конструктор и расширяю уникальными для каждой структуры полями.

**Comment by DmitryShvaika** [comment]
Тогда опять приходим к тому, что надо отличать функции-конструкторы от обычных функций.

**Comment by RedMammoth** [comment]
Связанная задача https://github.com/1C-Company/v8-code-style/issues/384

**Comment by marmyshev** [comment]
Предлагаю такой алгоритм:
1. Проверять что структура "внешняя" - т.е. создана в не текущей процедуры
2. Для внешних структур - запрещаем методы "`Структура.Очистить()`" если есть хотя бы один ключ в типе, "`Структура.Удалить(ИмяСуществующегоКлюча)`", "`Структура.Вставить(ИмяСуществующегоКлюча, ...)`" если указанный ключ.

Т.о. будет возможность безопасно расширять структуры новыми ключами. Запретим модификацию структуры с потенциальной сменой типа данных ключа.
Универсальные алгоритмы смогут манипулировать ключами структур как угодно.
