### ISSUE TITLE
В строгих типах неоправданно выдает ошибку на первый параметр функции ОткрытьФорму("ОбщаяФорма.МояФорма")

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/v8-code-style#1056]
### Описание ошибки

В строгих типах неоправданно выдает ошибку на первый параметр функции ОткрытьФорму("ОбщаяФорма.МояФорма")

![image](https://user-images.githubusercontent.com/54451084/176165442-23fc2c6a-c2eb-4d37-8b46-6f7756d6af1f.png)

Тип параметра указан верно - строка, однако Edt диагностирует ошибку.

### Как воспроизвести

1. Создать общую форму "МояФорма"
2. Создать клиентский общий модуль
3. Ввести текст

// @strict-types

Процедура МояПроцедура() Экспорт
	
	ОткрытьФорму("ОбщаяФорма.МояФорма");
	
КонецПроцедуры

4. Наблюдать ошибку

### Ожидаемое поведение

Ошибка не должна диагностироваться

### Лог рабочей области

[логи.zip](https://github.com/1C-Company/1c-edt-issues/files/9000463/default.zip)

### Версия 1С:EDT

2021.3.4

### Операционная система

Windows

### Дополнительная информация

Прилагаю архив тестового проекта
[test.zip](https://github.com/1C-Company/1c-edt-issues/files/9000466/test.zip)

**Comment by marmyshev** [comment]
Исправлено в https://github.com/1C-Company/v8-code-style/pull/1048
