### ISSUE TITLE
EDT не сообщает о повторяющихся id элементов в форме, что приводит к не работающим формам в рантайме

### ISSUE THREAD

**Issue by nikolay-martynov** [1C-Company/v8-code-style#1073]
### Описание ошибки

Сейчас в EDT может получиться форма, которая содержит в себе элементы, с одинаковыми id, работа такой формы в рантайме или не возможна, или порождает сложнопонимаемое поведение, разработчик на EDT сам не сможет сейчас никак докопаться, что в форме проблема, потеряет очень много времени.

### Как воспроизвести

При одновременной доработке одной формы двумя и более разработчиками может возникнуть ситуация, что появляются дубликаты среди идентификаторов элементов форм, для этого достаточно добавить каждому из разработчиков новый элемент формы. Наличие дубликатов среди идентификаторов элементов форм "ломает" форму в рантайме.
Бывают ситуации когда идентификатора у элемента нет - это тоже ошибка.

### Скриншоты

![image-2022-04-01-15-18-07-844](https://user-images.githubusercontent.com/13433348/179930775-3113c4c6-0932-44ad-b0d6-0a75f5cc4a87.png)

### Ожидаемое поведение

Сообщение об ошибке в окне "Ошибки конфигурации".

### Лог рабочей области

20.07.2022 11:24:32
{Справочник.Справочник1.Форма.ФормаЭлемента1.Форма(22,10)}: Ожидается имя области
#Область <<?>>ОбработчикиСобытийЭлементовТаблицыФормы//<ИмяТаблицыФормы>
{Справочник.Справочник1.Форма.ФормаЭлемента1.Форма(26,2)}: Пропущен оператор препроцессора Область (Region)
#<<?>>КонецОбласти

### Версия 1С:Code style V8

0.3.0

### Версия 1С:EDT

2021.2

### Операционная система

Windows

### Дополнительная информация

1C-Company/dt-project-checks#7
G5V8DT-22016

**Comment by marmyshev** [comment]
Делается в рамках задачи https://github.com/1C-Company/dt-project-checks/issues/7
