### ISSUE TITLE
Ложное отображение ошибки: notify-description-to-server-procedure

### ISSUE THREAD

**Issue by ilya2184** [1C-Company/v8-code-style#1085]
## Название/код проверки

Название проверки: `Процедура описания оповещения должна существовать и быть экспортной`
Код проверки: `notify-description-to-server-procedure`

Версия плагина: `0.3.0.116`

## Пример кода/метаданных содержащих ошибку

```
// В модуле формы объекта

&НаКлиенте
Процедура ЗаполнитьДокумент(Команда)
	ТекстВопроса = НСтр("ru = 'Перед заполнением суммы будут очищены, продолжить?'");
	Оповещение = Новый ОписаниеОповещения("ВопросЗаполнитьПоДоговоруЗавершение", ЭтотОбъект);
	ПоказатьВопрос(Оповещение, ТекстВопроса, РежимДиалогаВопрос.ДаНет, , КодВозвратаДиалога.Да);
КонецПроцедуры

&НаКлиенте
Процедура ВопросЗаполнитьПоДоговоруЗавершение(Результат, ДополнительныеПараметры) Экспорт
	
	Если Результат = КодВозвратаДиалога.Да Тогда
		//...
	КонецЕсли;
	
КонецПроцедуры
```

## Почему это НЕ ошибка

Потому что процедура существует и экспортная

## Дополнительные материалы
1 - маркер ошибки в дереве
2 - единственная "красная" ошибка
3 - нет маркера в коде
4 - процедура есть

Ошибка/предупреждение полностью исчезает
если использовать устаревшее ЭтаФорма вместо ЭтотОбъект
```
Оповещение = Новый ОписаниеОповещения("ВопросЗаполнитьПереданнымиКонтрагентуОСЗавершение", **ЭтаФорма**);
```
Очистка проекта не помогает, приложение версии 2022.1.0
В проекте внешней обработки не повторяется.
![image](https://user-images.githubusercontent.com/14931660/181349039-dd741dc4-2edf-4e67-8caf-22ac97c1a611.png)

**Comment by marmyshev** [comment]
По текущему примеру не воспроизводится. Никак, ни с `ЭтаФорма` ни `ЭтотОбъект`

**Comment by marmyshev** [comment]
@MaksimDzyuba Это может быть связано с экспортными методами при переходе на 2022.1? Может они портятся как-то?

**Comment by marmyshev** [comment]
@ilya2184 а если модуль модифицировать и сохранить, ошибка уходит?

**Comment by marmyshev** [comment]
Ошибку закрываю, т.к. проверка сама работает.

@ilya2184 если вдруг найдете стабильное воспроизведение, при котором в ЕДТ пропадают ссылки на экспортые методы - просьба зарегать в багтрекер ЕДТ.

**Comment by ilya2184** [comment]
@marmyshev 
У меня когда я ставлю ЭтаФорма - ошибка уходит, сохранение - не меняет результат
Когда возвращаю ЭтотОбъект "ошибка" вновь появляется (в кавычках потому что не очень понятно - если это ошибка тогда почему маркеров в коде нет, а если не ошибка - почему в списке есть.

**Comment by marmyshev** [comment]
Ок. спасибо за пояснения. 
То что в коде маркеров нет - как раз свидетельство что проверка работает правильно.

То что маркеры на панели в списке отображаются: одно из двух - либо панель не обновилась (попробуйте переоткрыть ее) либо маркеры всё-таки не обновляются (не удаляются) - это ошибка ЕДТ, но если сделать клин-билд проекта этих ошибок не будет.

**Comment by mrshadow300373** [comment]
@ilya2184, приветствую! В 2022.1.3 это не проявляется? У меня на работе аналогичное прямо один в один в 2021.3.4, думаю вот переходить на 2022.1.3 там или нет.
