### ISSUE TITLE
Стандарт 496: Чтение отдельных реквизитов объекта из базы данных

### ISSUE THREAD

**Issue by untou4** [1C-Company/v8-code-style#1088]
### Чтение отдельных реквизитов объекта из базы данных

https://its.1c.ru/db/v8std/content/496/hdoc/

`Напишите краткое название проверки`

**Английское название проверки**

`Напишите английское название проверки`

### Правило анализа кода/метаданных

Если в коде понятно что в переменной ссылочный тип и от него получается значение реквизита через точку, то это ошибка.

### Мета-информация (пожалуйста, заполните если знаете):

- Номер стандарта: 496
- Код проверки: `например: my-check-id`
- Тип ошибки: `PERFORMANCE`
- Критичность: `MAJOR`
- Код ошибки АПК: 

### Текст ошибки

Обращение к реквизитам объекта через точку от ссылки

### Пример некорректного решения

```bsl
Процедура ЗаполнитьКодИНаименованиеСтраны()
 
 СтранаСсылка = … // получаем ссылку на элемент справочника 
 КодСтраны = СтранаСсылка.Код; // первое обращение загружает объект целиком
 НаименованиеСтраны = СтранаСсылка.Наименование;
 
КонецПроцедуры
```

### Описание, почему так делать нельзя

Приводит к загрузке объекта из базы целиком, вместе с его табличными частями

### Пример корректного решения

```bsl
Процедура ЗаполнитьКодИНаименованиеСтраны()

 ЗначенияРеквизитов = ОбщегоНазначения.ЗначенияРеквизитовОбъекта(СтранаСсылка, "Код, Наименование");
 КодСтраны = ЗначенияРеквизитов.Код;
 НаименованиеСтраны = ЗначенияРеквизитов.Наименование;
 
КонецПроцедуры
```

### Дополнительные материалы
![image](https://user-images.githubusercontent.com/31420259/181494095-e88efa4a-7e7a-412f-b938-718159a5c925.png)

- [Ссылка на стандарт на сайте ИТС](https://its.1c.ru/...)
- Скриншоты с примерами некорректного состояния кода/метаданных
- Скриншоты с примерами исправленного состояния кода/метаданных

**Comment by artbear** [comment]
@marmyshev @iArtemv а почему вдруг у этой хорошей проверки важность стала незначительной?

в этом ишью написано Важная, а в ПР указано Minor

https://github.com/1C-Company/v8-code-style/blob/master/bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ReadingAttributesFromDataBaseCheck.java#L88

**Comment by iArtemv** [comment]
Скорее всего по ошибке, зафиксировал
В своем проекте можно в настройках управлять критичностью проверок, так как это значение по умолчанию
