### ISSUE TITLE
Стандарт 741: Обращение к опциональному параметру формы

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#1120]
### Название проверки

`Обращение к опциональному параметру формы`

**Английское название проверки**

`Access to options form parameter`

### Правило анализа кода/метаданных

Если в коде модуля формы обращение через `Параметры.Свойство("ИмяПараметра")` - нужно проверять наличие параметра на форме - если существует - то заменять на прямое обращение т.к. такой код не имеет смысла.

Решить, как проверять вариант когда параметра на форме не существует - требовать заменять всегда?

### Мета-информация (пожалуйста, заполните если знаете):

- Номер стандарта: `741`
- Код проверки: `optional-form-parameter-access`
- Тип ошибки:  `CODE_STYLE` 
- Критичность:  `MINOR`
- Код ошибки АПК: `-`

### Параметры проверки

- Список имен параметров исключения
- Регулярное выражение исключения для полного имени формы

### Пример некорректного решения

```bsl
&НаСервере
Процедура ПриСозданииНаСервере(Отказ, СтандартнаяОбработка)
    ФамилияИмяОтчество = Неопределено;
    Если Параметры.Свойство("ФамилияИмяОтчество", ФамилияИмяОтчество) Тогда
        Объект.Наименование = ФамилияИмяОтчество;
    КонецЕсли;
КонецПроцедуры
```

### Описание, почему так делать нельзя

3. Параметры формы следует объявлять явно на закладке Параметры редактора формы. В таком случае в коде обработчика ПриСозданииНаСервере не требуется проверять наличие свойств у структуры Параметры, а сам состав параметров формы явно задекларирован (поэтому их не требуется восстанавливать, изучая весь код обработчика ПриСозданииНаСервере).

### Пример корректного решения

```bsl
&НаСервере
Процедура ПриСозданииНаСервере(Отказ, СтандартнаяОбработка)
    Объект.Наименование = Параметры.ФамилияИмяОтчество;
КонецПроцедуры
```

### Дополнительные материалы

- [Открытие параметризированных форм](https://its.1c.ru/db/v8std#content:741:hdoc)

**Comment by VAGoncharov** [comment]
Взял в работу.
