### ISSUE TITLE
Добавить имя элемента формы в сообщение проверки form-list-ref-user-visibility-enabled

### ISSUE THREAD

**Issue by adminimusRU** [1C-Company/v8-code-style#1127]
### Описание проблемы

В большинстве случаев на формах списка всего один динамический список и всё очевидно. Но бывают сложные формы, содержащие множество динамических списков, и в таких случаях неясно, на каком именно списке диагностирована ошибка, приходится перебирать все вручную.
Пример формы с множеством динамических списков - `Обработка.ПодборТоваровВДокументПродажи.Форма.Форма` из состава УТ/ERP.

### Описание решения проблемы

Добавить в сообщение имя элемента формы:
`У поля "Ссылка" таблицы динамического списка %ИмяЭлемента% не отключена пользовательская видимость`

**Comment by marmyshev** [comment]
@adminimusRU нужно пояснение - а что мешает кликнуть на ошибке и сразу перейти к элементу формы на котором ошибка (там же на элементе формы должна подсвечиваться иконка с ошибкой)?

**Comment by adminimusRU** [comment]
> @adminimusRU нужно пояснение - а что мешает кликнуть на ошибке и сразу перейти к элементу формы на котором ошибка (там же на элементе формы должна подсвечиваться иконка с ошибкой)?

переход к элементу для этой ошибки у меня не работает. Вчера когда проверял, по клику на ошибке каждый раз переходило к разным элементам формы. Сегодня вообще никуда переходить не хочет, и в журнале ошибок ничего не добавляется. При этом по ошибкам в коде модуля переходит корректно на нужную строку.
Иконки с ошибками у меня на элементах формы тоже нет, только на самой форме. Возможно тут очередной баг из-за масштабирования шрифтов. Или может быть есть настройка какая-то для включения иконок с ошибками?
Кроме того, иконки сами по себе не помогут как раз на больших сложных формах с кучей элементов в несколько слоев.

**Comment by marmyshev** [comment]
@vadimeg прошу подключиться: не работает переход к элементу, не работает декорация по ошибкам на элементах формы.

**Comment by marmyshev** [comment]
@olgabozhko сможешь добавить имя элемента в сообщение?

**Comment by vadimeg** [comment]
> прошу подключиться
Оно как бы в процессе, задача есть, исследуется. Там не все так просто в текущем механизме навигации и фокусировки. Для начала хорошо бы с location разобраться, иначе информацию о целевом элементе брать неоткуда. Наличие в маркере доп. инфо в виде FQN элемента может привести к деградации производительности, маркеры старались делать минималистичными. Пока дискуссия в реквесте приостановлена в связи с наличием более приоритетных задач.

**Comment by olgabozhko** [comment]
> сможешь добавить имя элемента в сообщение?
Добавлю, можно на меня назначить.
