### ISSUE TITLE
Unknown check id "com.e1c.v8codestyle.bsl:doc-comment-redundant-parameter-section"

### ISSUE THREAD

**Issue by AndreyDanilov-nn** [1C-Company/v8-code-style#1157]
### Описание ошибки

При выполнении проверки спамит `java.lang.IllegalStateException: Unknown check id "com.e1c.v8codestyle.bsl:doc-comment-redundant-parameter-section`

### Как воспроизвести

.

### Ожидаемое поведение

отсутствие ошибки

### Лог рабочей области

[log.txt](https://github.com/1C-Company/v8-code-style/files/9617296/log.txt)

### Версия 1С:Code style V8

0.3.0.158

### Версия 1С:EDT

2022.1.2

### Операционная система

Windows

### Дополнительная информация

Возможно проблема в конфе, но что искать/править не очень понятно

**Comment by marmyshev** [comment]
Подозреваю, что после повторного запуска такое исключение не возникает больше?

**Comment by AndreyDanilov-nn** [comment]
К сожалению уже не вспомню. На данный момент эта ошибка перестала появляться
