### ISSUE TITLE
Проверка module-self-reference срабатывает в модуле объекта

### ISSUE THREAD

**Issue by unichkin** [1C-Company/v8-code-style#1171]
### Описание ошибки

На ИТС когда-то натыкался на правило, запрещающее использовать обращение к реквизитам ЭтотОбъект, находясь в форме, и с ним согласен - в форме это ни к чему, проверка с этой стороны замечательная.
Но почему она помимо формы срабатывает и для **модуля объекта**? 
![image](https://user-images.githubusercontent.com/10799597/194757583-0039f959-ed9b-4491-97d5-bfbcaa53acbd.png)

В стандартах запрета не находил, и вроде бы здесь кому как удобнее. 

### Ожидаемое поведение

Предлагаю добавить опцию, чтобы можно было пропускать проверки модулей объектов. Плюсы обращения к реквизитам через ЭтотОбъект: 
- позволяет легко отличать реквизиты объекта от локальных переменных
- при переносе кода - например из события обработки заполнения в доп. обработку заполнения объекта - позволяет легко и просто переименовать "ЭтотОбъект" на именование переменной заполняемого объекта

### Версия 1С:EDT

 Ruby 2022.1.2

### Операционная система

Windows

**Comment by VAGoncharov** [comment]
Взял в работу

**Comment by marmyshev** [comment]
Модуль формы, модуль объекта или общий модуль -  для данного правила вообще никакого значения не имеет. Если разобраться в смысле правила - это запрет на излишнее обращение к объекту через "ЭтотОбъект" - что захламляет код.

В модуле объекта, например: `ЭтотОбъект.КорректироватьНалоговуюСтоимость = Ложь;` и `КорректироватьНалоговуюСтоимость = Ложь;` - являются идентичным кодом. Собственно, в этом и смысл проверки - избавиться от такого излишнего обращения.

**Comment by unichkin** [comment]
Добрый день. По поводу "захламляет код" - прошу привести регламент ИТС, подтверждающий эту фразу. Иначе - это Ваше личное мнение. А мое личное мнение, что в модуле объекта это удобно, и не только не захламляет код, но и помогает его сопровождать. Это во-первых позволяет легко выделять реквизиты объекта от локальных переменных. Во-вторых при переносе кода - например из события обработки заполнения в доп. обработку заполнения объекта - позволяет легко и просто переименовать "ЭтотОбъект" на именование переменной заполняемого объекта.
Что реально сейчас захламляет код - это куча желтых блоков от этой проверки. Которая для форм вполне уместна, и хотелось бы ее оставить. Но с таким подходом она у нас на тек. момент отключена.

**Comment by marmyshev** [comment]
> По поводу "захламляет код" - прошу привести регламент ИТС, подтверждающий эту фразу

Если речь про стандарт на ИТС - то я такого не нашел. Однако, не нужно ожидать что любое "здравомыслие" должно быть застандартизировано. 

Эта проверка была резалиозвана по задаче #310 - это перенос идентичной функциональности из АПК. 

В данном случае, такая проверка на "здравый смысл" в АПК была привязана к общему стандарту "здравых смыслов" :) №467 - это никак не добавляет веса этой проверке, если цепляться за буквы на ИТС - так как стандарт обо всём и ни чем конкретно.

К сожалению, какой либо дополнительной информации по этой проверки тоже нигде не описано в АПК.

Вам лично, это правило не подходит (или не нравится) - тут мы не спорим о личных вкусах :) Вы просто отключайте это правило и ваш проект имеет право не соблюдать любой стандарт, любую проверку, по любым причинам.

> А мое личное мнение, что в модуле объекта это удобно

Предлагаю ваш кейс добавить в описание выше, чтобы было понятно для чего нужна такая доработка в проверке.  ИМХО, частичное соблюдение этого правила лучше чем полное отключение.

**Comment by unichkin** [comment]
Добрый день, добавил в описание.
