### ISSUE TITLE
В строгих типах колонки дерева значений не наследуются для подчиненных строк

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/v8-code-style#1221]
### Описание ошибки

В строгих типах колонки дерева значений не наследуются для подчиненных строк
В данном случае определена колонка Ключ и для строк коллекции edt ее "видит", однако для подчиненных строк уже этой колонки в типах нет.

![image](https://user-images.githubusercontent.com/54451084/205700347-e70a513a-deb0-4468-864b-52f4dec301f6.png)

### Как воспроизвести

1. Ввести код

```
// @strict-types

#Область ПрограммныйИнтерфейс

// Вывести операторы.
// 
// Параметры:
//  СтрокиДерева - КоллекцияСтрокДереваЗначений из СтрокаДереваЗначений:
//  	* Ключ - Строка
//
Процедура ВывестиОператоры(СтрокиДерева) Экспорт

	СтрокаОператора = СтрокиДерева.Добавить();
	СтрокаОператора.Ключ = "Операторы: ";
	
	СтрокаПодчиненныеОператоры = СтрокаОператора.Строки.Добавить();
	СтрокаПодчиненныеОператоры.Ключ = "Оператор";

КонецПроцедуры

#КонецОбласти

```
2. Наблюдать ошибку

### Ожидаемое поведение

Колонки должны наследоваться для коллекции подчиненных строк дерева, т.к. в одном дереве не может быть на разных уровнях разное число колонок.

### Лог рабочей области

не требуется

### Версия 1С:Code style V8

Ruby 2022.1.4

### Версия 1С:EDT

2022.1.4

### Операционная система

Windows

**Comment by RedMammoth** [comment]
Похоже подобная ошибка и с ВыборкойИзРезультатаЗапроса

![image](https://user-images.githubusercontent.com/64589646/234239845-5211ed95-33b0-4f41-973a-5c7efab59403.png)

**Comment by MaksimDzyuba** [comment]
Поправил, скорее всего войдет в 2023.1, но не факт, что в первую тестовую
![bandicam-2023-05-03-18-18-03-640](https://user-images.githubusercontent.com/77277424/235961851-3467f5be-295e-4611-9854-820250cb36ef.gif)
