### ISSUE TITLE
Ложное срабатывание проверки: invocation-parameter-type-intersect

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/v8-code-style#1222]
## Название/код проверки

Код проверки: `invocation-parameter-type-intersect`

Версия плагина: `2022.1.4`

## Пример кода/метаданных содержащих ошибку

```bsl
// @strict-types 

#Область ПрограммныйИнтерфейс

Процедура Тест() Экспорт

	ИмяМенеджера = "РегистрыСведений";
	
	КоллекцияМетаданных = Метаданные[ИмяМенеджера]; // КоллекцияОбъектовМетаданных
	
	Для Каждого МетаданныеОбъекта Из КоллекцияМетаданных Цикл
		
		Периодический = РегистрСведенийПериодический(МетаданныеОбъекта);
		
		Периодический = Периодический;
		МетаданныеОбъекта = МетаданныеОбъекта;
		
	КонецЦикла;

КонецПроцедуры

// Регистр сведений периодический.
// 
// Параметры:
//  МетаданныеРегистра - ОбъектМетаданныхРегистрСведений - Метаданные регистра
// 
// Возвращаемое значение:
//  Булево - Регистр сведений периодический
//
Функция РегистрСведенийПериодический(МетаданныеРегистра) Экспорт
	
	Возврат МетаданныеРегистра.ПериодичностьРегистраСведений <> 
				Метаданные.СвойстваОбъектов.ПериодичностьРегистраСведений.Непериодический;
	
КонецФункции

#КонецОбласти

```

![image](https://user-images.githubusercontent.com/54451084/205885051-f0198d22-b9e9-4ad1-a888-096ab4595e85.png)

## Почему это НЕ ошибка

Тип ОбъектМетаданных "содержит в себе тип" ОбъектМетаданныхРегистрСведений. Типы пересекаются - ошибки быть не должно.

**Comment by RedMammoth** [comment]
```
// @strict-types 

#Область ПрограммныйИнтерфейс

Процедура Тест() Экспорт

	КоллекцияМетаданных = Метаданные.РегистрыСведений;
	Для Каждого МетаданныеОбъекта Из КоллекцияМетаданных Цикл
		Периодический = РегистрСведенийПериодический(МетаданныеОбъекта);
		Периодический = Периодический;
		МетаданныеОбъекта = МетаданныеОбъекта;
	КонецЦикла;

КонецПроцедуры

// Регистр сведений периодический.
// 
// Параметры:
//  МетаданныеРегистра - ОбъектМетаданныхРегистрСведений - Метаданные регистра
// 
// Возвращаемое значение:
//  Булево - Регистр сведений периодический
//
Функция РегистрСведенийПериодический(МетаданныеРегистра) Экспорт
	
	Возврат МетаданныеРегистра.ПериодичностьРегистраСведений <> 
				Метаданные.СвойстваОбъектов.ПериодичностьРегистраСведений.Непериодический;
	
КонецФункции

#КонецОбласти
```

Так работает. 
Так тоже:
// @strict-types 

#Область ПрограммныйИнтерфейс

Процедура Тест() Экспорт

	ИмяМенеджера = "РегистрыСведений";
	
	КоллекцияМетаданных = Метаданные[ИмяМенеджера]; // КоллекцияОбъектовМетаданных Из ОбъектМетаданныхРегистрСведений
	
	Для Каждого МетаданныеОбъекта Из КоллекцияМетаданных Цикл
		
		Периодический = РегистрСведенийПериодический(МетаданныеОбъекта);
		
		Периодический = Периодический;
		МетаданныеОбъекта = МетаданныеОбъекта;
		
	КонецЦикла;

КонецПроцедуры

// Регистр сведений периодический.
// 
// Параметры:
//  МетаданныеРегистра - ОбъектМетаданныхРегистрСведений - Метаданные регистра
// 
// Возвращаемое значение:
//  Булево - Регистр сведений периодический
//
Функция РегистрСведенийПериодический(МетаданныеРегистра) Экспорт
	
	Возврат МетаданныеРегистра.ПериодичностьРегистраСведений <> 
				Метаданные.СвойстваОбъектов.ПериодичностьРегистраСведений.Непериодический;
	
КонецФункции

#КонецОбласти

**Comment by RedMammoth** [comment]
Я в телеграмм-канале не правильно понял, подумал о другой проблеме. Заведу на нее задачу отдельно. 
```
Процедура Тест() Экспорт
	ТаблицаФормы = Неопределено; // ТаблицаФормы
	ТФ_ДляТаблицыЗначений = Неопределено; // РасширениеТаблицыФормыДляТаблицыЗначений
КонецПроцедуры
```
Для ТаблицыФормы подсказка полная:
![image](https://user-images.githubusercontent.com/64589646/205976484-98763e5e-cb5c-49d6-ae9f-1d7cdc86a9f0.png)
А для расширения только уникальные методы и свойства и приходится указывать оба типа, что избыточно:
![image](https://user-images.githubusercontent.com/64589646/205976762-1f2b112f-4a48-48ad-a151-e3566aa75040.png)

**Comment by DmitryShvaika** [comment]
принято, спасибо
