### ISSUE TITLE
Ложное срабатывание проверки invocation-parameter-type-intersect для СтрокаТабличнойЧасти и Документ/Справочник/ОбработкаТабличнаяЧастьСтрока

### ISSUE THREAD

**Issue by RedMammoth** [1C-Company/v8-code-style#1227]
## Название/код проверки

Код проверки: `invocation-parameter-type-intersect`

Версия плагина: `0.4.0.131`

## Пример кода/метаданных содержащих ошибку

```bsl
// @strict-types
#Область ПрограммныйИнтерфейс

Процедура Тест() Экспорт
	ПроверкаТипаТЧ(Справочники.Справочник1.СоздатьЭлемент().ТабличнаяЧасть1);
	ПроверкаТипаТЧ(Документы.Документ1.СоздатьДокумент().ТабличнаяЧасть1);
	ПроверкаТипаТЧ(Обработки.Обработка1.Создать().ТабличнаяЧасть1);
КонецПроцедуры

#КонецОбласти

#Область СлужебныеПроцедурыИФункции

// Параметры:
//  Параметр - СтрокаТабличнойЧасти
Процедура ПроверкаТипаТЧ(Параметр)
	Возврат;
КонецПроцедуры

#КонецОбласти
```

![image](https://user-images.githubusercontent.com/64589646/210107474-2afb3a42-4f46-4ff7-8524-2a8ed28ca392.png)

## Почему это НЕ ошибка

Мне кажется, что тип СтрокаТабличнойЧасти является общим типом для частного ДокументТабличнаяЧастьСтрока и т.п.
Поэтому при написании метода, работающего с любой строкой табличной части, в качестве типа параметра указываю общий тип и ожидаю, что передача частного пройдет без ошибок.

Если я не прав на счет общего типа, подскажите, пожалуйста какой использовать. В контент-ассисте ничего подходящего больше не нашел.

**Comment by marmyshev** [comment]
Это не ошибка - т.к. `Справочники.Справочник1.СоздатьЭлемент().ТабличнаяЧасть1` - это объект Табличной части. А входящий параметр - `СтрокаТабличнойЧасти` - т.е. ничего общего. Проверка срабатывает правильно.

Закрываем?

**Comment by RedMammoth** [comment]
Да, моя невнимательность
