### ISSUE TITLE
Ложное срабатывание проверки typed-value-adding-to-untyped-collection на реквизитах и свойствах элементов формы

### ISSUE THREAD

**Issue by adminimusRU** [1C-Company/v8-code-style#1231]
## Название/код проверки

Код проверки: `typed-value-adding-to-untyped-collection`

Версия плагина: `0.4.0.131`

## Пример кода/метаданных содержащих ошибку

Проверка срабатывает при добавлении значений в реквизиты формы с типами `СписокЗначений`, а также в свойства элементов формы, являющихся коллекциями. Например свойство `ВыделенныеДаты` поля календаря с типом `Массив` считается нетипизированным.

```bsl
Элементы.ПолеКалендаря.ВыделенныеДаты.Добавить(ТекущаяДата());
РеквизитСписокЗначений.Добавить("НовоеЗначение");
```

## Почему это НЕ ошибка

Отсутствует возможность изначально задать типы элементов коллекций для таких случаев. Указание типа значений элементов для списка значений в реквизите формы почему-то не учитывается, коллекция всё равно считается нетипизированной.
Приходится при каждом обращении подавлять ошибку либо использовать промежуточные переменные.

**Comment by adminimusRU** [comment]
Также проверка постоянно срабатывает при работе с соответствиями и списками значений в коде. Для этих коллекций сейчас нет простой возможности задать тип, только через функцию-конструктор, что приводит к раздуванию кода.

Кроме того, неясно почему проверка имеет критичность "Значительная", в то время как аналогичная по смыслу проверка `structure-consructor-value-type` является незначительной.

**Comment by marmyshev** [comment]
Закрываем, т.к. будет реализовано в ЕДТ.
