### ISSUE TITLE
Опечатка в панели Структура модуля в свойствах проекта

### ISSUE THREAD

**Issue by artbear** [1C-Company/v8-code-style#1245]
### Описание ошибки

Ошибочное "или **снемите** флажок, чтобы удалить" вместо "снимите"

![image](https://user-images.githubusercontent.com/2920817/215320786-c1eea543-885b-42e3-8d3f-c3a0fd59f2cc.png)

### Как воспроизвести

открыть панель

### Ожидаемое поведение

.

### Лог рабочей области

.

### Версия 1С:Code style V8

0.4.0

### Версия 1С:EDT

2021.1.5

### Операционная система

Windows

**Comment by RedMammoth** [comment]
Исправлена https://github.com/1C-Company/v8-code-style/commit/629cfddc478a379db175a176e64dd034af27f526
