### ISSUE TITLE
Для модулей повторного использования избыточно выдается ошибка для функций / процедур области СлужебныйПрограммныйИнтерфейс подобласть УстаревшиеПроцедурыИФункции

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/v8-code-style#1265]
### Описание ошибки

Для модулей повторного использования избыточно выдается ошибка для функций / процедур области СлужебныйПрограммныйИнтерфейс подобласть УстаревшиеПроцедурыИФункции

![image](https://user-images.githubusercontent.com/54451084/216758610-1a22bd04-94e1-4bfd-b451-a4ce5560d736.png)

Область ПрограммныйИнтерфейс, которую требует Edt в модулях повторного использования запрещена

![image](https://user-images.githubusercontent.com/54451084/216758656-c30bccb6-b562-4782-ba2a-b4569d6e1a40.png)

Еще момент: если вместо процедуры будет функция и возвращаемое значение будет описано ссылкой, то при попытке подавить эту ошибку будет выдана новая

![image](https://user-images.githubusercontent.com/54451084/216760427-95fa5062-e76a-440e-a376-066885ff77a0.png)

### Как воспроизвести

1. Создать общий модуль повторного использования
2. Ввести текст

```
#Область СлужебныйПрограммныйИнтерфейс

#Область УстаревшиеПроцедурыИФункции

// Устарела.
// Ааа.
Процедура ааа() Экспорт
	
	а = 1;
	а = а;
	
КонецПроцедуры

#КонецОбласти

#КонецОбласти
```

3. Наблюдать ошибку

### Ожидаемое поведение

Ошибка не должна генерироваться

### Лог рабочей области

не требуется

### Версия 1С:EDT

Ruby 2022.2.3

### Операционная система

Windows

**Comment by iArtemv** [comment]
Была исправлена в рамках другой задачи.
