### ISSUE TITLE
Требуется уточнить проверку структуры модуля

### ISSUE THREAD

**Issue by unichkin** [1C-Company/v8-code-style#1303]
### Описание ошибки

Согласно ИТС https://its.1c.ru/db/v8std/content/680/hdoc
События менеджера "ОбработкаПолученияПолейПредставления", "ОбработкаПолученияПредставления" в некоторых случаях (если нужен вызов сервера) нельзя размещать внутри директив "#Если Сервер Или ТолстыйКлиентОбычноеПриложение Или ВнешнееСоединение Тогда"
При этом проверка ругается:
![image](https://user-images.githubusercontent.com/10799597/225830993-bdeeac9d-6e93-4007-bc14-7a62f71b16b1.png)

Если разместить их в область "ОбработчикиСобытий", снова ошибка:
![image](https://user-images.githubusercontent.com/10799597/225831269-87b6190a-8ba8-4985-aa3c-5426932fb74f.png)

### Как воспроизвести

В описании

### Ожидаемое поведение

Ошибки быть не должно - не знаю как правильнее сделать. но кажется не стоит требовать размещения этих событий в стандартную область. Могут быть другие события, которые должны быть размещены внутри директив, и тогда нужно создавать две области "ОбработчикиСобытий", что избыточно как мне кажется. Это особенный случай, для этих событий предлагаю проверки опускать.

### Лог рабочей области

-

### Версия 1С:EDT

Ruby 2022.2.4

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by iArtemv** [comment]
@unichkin предложение разместить код следующим образом

```bsl

#Если Сервер Или ТолстыйКлиентОбычноеПриложение Или ВнешнееСоединение Тогда

#Область ПрограммныйИнтерфейс
#КонецОбласти

#КонецЕсли

#Область ОбработчикиСобытий

#Если Сервер Или ТолстыйКлиентОбычноеПриложение Или ВнешнееСоединение Тогда

Процедура ОбработкаПолученияФормы(...)
КонецПроцедуры

#КонецЕсли

Процедура ОбработкаПолученияПолейПредставления(...)
КонецПроцедуры

Процедура ОбработкаПолученияПредставления(...)

#Если Сервер Или ТолстыйКлиентОбычноеПриложение Или ВнешнееСоединение Тогда
...
#Иначе
...
#КонецЕсли

КонецПроцедуры


#Если Сервер Или ТолстыйКлиентОбычноеПриложение Или ВнешнееСоединение Тогда

#Область СлужебныйПрограммныйИнтерфейс

#КонецОбласти

#КонецЕсли
```

**Comment by unichkin** [comment]
Да ну, никто так делать не будет. Мне самому проще в коде проверку отключить, чем городить такой огород, Вы уж извините. Суть моего исходного предложения в том, чтобы вообще отключить проверки структуры модуля для этих событий. Их по ИТС можно размещать как внутри директив \ стандартных областей, так и вне их.
Можно уточнить - если события внутри директивы, то они должны быть в области ОбработчикиСобытий. Иначе не проверять.

**Comment by unichkin** [comment]
Ну, или вот в БСП 3.1.7 сейчас нашел - область "ОбработчикиСобытий" вынесена в отдельный блок, с проверкой директив внутри нее.
![image](https://user-images.githubusercontent.com/10799597/226537650-7341677c-c053-4fd6-8524-10ee467c0ae5.png)

Хотя мне и это кажется диким.. Но уж лучше так, чем каждую стандартную область помещать в свою директиву.

**Comment by unichkin** [comment]
@iArtemv просмотрел БСП, понял что свои примеры Вы видимо оттуда и брали, там тоже такой подход... Т.е. обработчики размещаются в порядке следования, и обрамляются директивами если есть разрыв. Невесело..

**Comment by iArtemv** [comment]
Можете уточнить где в стандарте говорится что данные области могут быть расположены вне стандартной области?

**Comment by unichkin** [comment]
Нигде не говорится, буду делать как в БСП, спасибо за примеры. Давайте закроем тогда эту задачу.
