### ISSUE TITLE
Ложное срабатывание проверки: doc-comment-field-type

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/v8-code-style#1310]
## Название/код проверки

Код проверки: doc-comment-field-type

Версия плагина: Ruby 2022.2.5

## Пример кода/метаданных содержащих ошибку

```bsl

// @strict-types

#Область ПрограммныйИнтерфейс

// Конструктор1.
// 
// Возвращаемое значение:
//  Структура - Конструктор1:
// 		* Поле - Строка -
//
Функция Конструктор1() Экспорт
	
	Данные = Новый Структура;
	Данные.Вставить("Поле", "");
	
	Возврат Данные;
	
КонецФункции

// Моя процедура.
// 
// Параметры:
//  а - см. Конструктор1
//  в - Строка
//
Процедура МояПроцедура(а, б) Экспорт
	
	Данные1 = Конструктор1();

	Если 1=1 Тогда
		
	КонецЕсли;
		
	Данные1.Поле = "значение";	
	
КонецПроцедуры

#КонецОбласти
```

![image](https://user-images.githubusercontent.com/54451084/229046209-3606e16a-392d-4072-bae9-f4328b9f04a5.png)

## Почему это НЕ ошибка

Тип первого параметра определен. Ошибка возникает из-за второго параметра, когда его имя отличается от использованного в процедуре / функции. А первый параметр описан как ссылка

**Comment by marmyshev** [comment]
Это не ошибка т.к. `в - Строка` - это текст описания следующий после ссылки. Такого формата
 `ИмяПараметра - См. Ссылка - Описане` не предусмотрено в ЕДТ на текущий момент, но кажется было пожелание на доработку. Здесь не важно что описание многострочное, а на второй строке написано нечто похожее на параметры...

**Comment by DmitryShvaika** [comment]
ок, закрою задачу тогда
