### ISSUE TITLE
Ложное срабатывание проверки: ConsecutiveEmptyLinesCheck

### ISSUE THREAD

**Issue by TimBasil** [1C-Company/v8-code-style#1311]
Проверка последовательности пустых строк срабатывает там, где пустых строк нет или есть только одна пустая строка.

![image](https://user-images.githubusercontent.com/129489899/229048575-b5c49499-21c0-4a60-9f62-07f456f4a9b5.png)

![image](https://user-images.githubusercontent.com/129489899/229048903-16e55e35-a8d3-4f2d-9153-0855cf11bf0b.png)

**Comment by TimBasil** [comment]
После закрытия - открытия EDT не воспроизводится.

**Comment by iArtemv** [comment]
Ошибка не воспроизвелась
