### ISSUE TITLE
doc-comment-field-type-strict: некорректное диагностическое сообщение пользователю

### ISSUE THREAD

**Issue by VAGoncharov** [1C-Company/v8-code-style#1321]
### Описание ошибки

Имеем функцию, которая возвращает Структуру. Структура имеет 3 ключа типа ТаблицаЗначений. Генерируем документирующий комментарий к функции, получаем следующий вид:
![Снимок экрана 2023-04-17 172234](https://user-images.githubusercontent.com/1153965/233649319-a96cf2b4-b2d8-485b-baea-3d93beb719ac.png)

### Как воспроизвести

-

### Ожидаемое поведение

Ожидается, что EDT вместо * выведет имя колонки ТЗ, которая еще не описана.
Возможно, проблема не в диагностическом сообщении, а в том, что неправильно парсятся описанные выше возвращаемые значения.

### Лог рабочей области

-

### Версия 1С:Code style V8

0.3.0.165

### Версия 1С:EDT

2022.1.5

### Операционная система

Windows

**Comment by marmyshev** [comment]
В Код-стайле нет парсинга текста - мы просто проверяем модель данных. ЕДТ предоставляет модель.

Предлагаю добавить скриншот из панели структуры документирующего комментария.

**Comment by marmyshev** [comment]
Сходу, это не похоже на результат генератора док.комментов.

Формат:

// ** ПолеТЗ - ТипКолонки - описание

Другие сокращения формата (например отсутствие типа или отсутствие описания, или оба) - это не факт что поддерживается в ЕДТ во всех местах. Т.е. по умолчанию нужно писать в полном формате.

Откуда взят этот док.коммент?

**Comment by VAGoncharov** [comment]
Док комментарий сгенерирован EDT через Ctrl+Alt-D. Типы колонок ТЗ не определились, потому что колонки ТЗ в коде описываются через ОписаниеТипов, EDT видимо не умеет определять тип в таком случае:
![image](https://user-images.githubusercontent.com/1153965/234213818-b9c57072-6c17-492d-a7db-0fbac2f14d56.png)

В панели все отражается корректно, пример:
![image](https://user-images.githubusercontent.com/1153965/234213940-3aa72ebd-6663-405e-9c9d-7dca8bf66861.png)

Только что проверил, в версии EDT **2022.2.5** выводятся сообщения с правильным именем поля:
![image](https://user-images.githubusercontent.com/1153965/234214488-4336b35f-7699-4e73-8976-dff3f2a03d9a.png)
Ишуз закрываю.
