### ISSUE TITLE
Стандарт 531: Реквизит "Комментарий" имеет недопустимый тип.

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#133]
### Название проверки
`Реквизит "Комментарий" имеет недопустимый тип.`

**Английское название проверки**
`??`

### Правило анализа кода/метаданных

Найти во всех документах реквизит с наименование  **Комментарий**  и проверить что он строка неограниченной длины.
Включено свойство мультистрочное редактирование.

### Мета-информация (пожалуйста, заполните если знаете):
- Номер стандарта: `531`
- Код проверки: `??my-check-id`
- Тип ошибки: `ERROR` `SECURITY` `PERFORMANCE`  `WARNING` `PORTABILITY` `LIBRARY_DEVELOPMENT_AND_USAGE` `CODE_STYLE` `UI_STYLE` `SPELLING`
- Критичность: `BLOCKER` `CRITICAL` `MAJOR` `MINOR` `TRIVIAL`
- Код ошибки АПК: `109`

#### Параметры проверки
- Имена реквизитов через запятую, которые следует проверять. По умолчанию "Комментарий, Comment"
- Галка проверки реквизитов в справочниках, если добавлено - по умолчанию `Ложь`.
- Галка проверки реквизитов в документах, по умолчанию `Истина`.

#### Текст ошибки
`Реквизит "Комментарий" имеет недопустимый тип.`

#### Пример некорректного решения
- NA

#### Описание, почему так делать нельзя

1\. Для всех документов рекомендуется создавать реквизит **Комментарий**
(строка неограниченной длины). В этом реквизите пользователи могут
записывать по документу различные заметки служебного характера, которые
не относятся к прикладной специфике документа (например, причина пометки
на удаления и т.п.). Доступ к реквизиту для пользователей должен быть
настроен также как и к самому документу (если документ доступен только
для чтения, то и комментарий – только для чтения; если же есть право
записи документа, то и значение реквизита также можно изменять).

#### Пример корректного решения
- NA

#### Дополнительные материалы

- [Реквизит "Комментарий" у документов](https://its.1c.ru/db/v8std#content:531:hdoc:1)

**Comment by marmyshev** [comment]
@VAGoncharov желательно отписываться в задаче, что ты начал над ней работать - чтобы никто параллельно н взял в работу ее же... и тогда можно ее назначить на тебя (пока не отпишешься невозможно)

**Comment by VAGoncharov** [comment]
@marmyshev Взял в работу.
