### ISSUE TITLE
Описание значений Соответствия

### ISSUE THREAD

**Issue by KamranV21** [1C-Company/v8-code-style#1331]
### Описание проблемы

Добавить возможность указывать детальное описание для значения из Соответствия в том случае, если его ключ это некая предопределенная строка.

### Описание решения проблемы

// Новое соответствие.
// 
// Возвращаемое значение:
//  Соответствие Из КлючЗначение
// * Ключ - "А"
// * Значение - Число
// * Ключ - "Б"
// * Значение - Булево
// * Ключ - "В"
// * Значение - Массив из Строка
// * Ключ - Строка
// * Значение - Строка
Функция НовоеСоответствие()

### Дополнительная информация

Бывает нужно, например, при чтении из JSON, когда чтение в структуру невозможно из-за того, что имя ключа не соответствует правилам написания ключа в 1С. 

Также заранее зная имена ключей можно было бы выводить контекстную подсказку при работе с соответствием данного типа.

**Comment by marmyshev** [comment]
Как это в коде собираетесь использовать?

Со структурой - ключи являются частью кода.

В то же время если к структуре обращаться через метод Структура.Свойство(...) - то никакой типизации, аналогично как и Структура["ИмяКлюча"] - тоже никакой типизации. Так же можно записать Структура[ПеременнаяКлюча] - в переменной может содержать любое значение, поэтому никакой типизации значения.

Но, это задача к ЕДТ, а не к Код-стайлу
