### ISSUE TITLE
Некорректная работа: md-object-attribute-comment-not-exist

### ISSUE THREAD

**Issue by REset49** [1C-Company/v8-code-style#1334]
### Описание ошибки

Срабатывает для справочников даже при отключенном "Проверять справочники".

### Как воспроизвести

1. В настройках валидации md-object-attribute-comment-not-exist отключить "Проверять справочники".
2. Добавить справочник

### Скриншоты
![image](https://github.com/1C-Company/v8-code-style/assets/92163852/b06d0a7e-e8a3-4d60-aea8-a25b224af1ce)

### Ожидаемое поведение

Проверка для справочников не должна срабатывать при отключении.

### Лог рабочей области

в

### Версия 1С:Code style V8

0.5.0.128

### Версия 1С:EDT

2023.1.0

### Операционная система

Windows

**Comment by VAGoncharov** [comment]
Ошибка поправлена

**Comment by REset49** [comment]
Ничего не изменилось на свежей 2023.1.1

![image](https://github.com/1C-Company/v8-code-style/assets/92163852/440539a6-c9d6-45db-9335-19c65beab6e0)

**Comment by VAGoncharov** [comment]
> Ничего не изменилось на свежей 2023.1.1
> 
> ![image](https://user-images.githubusercontent.com/92163852/260393607-440539a6-c9d6-45db-9335-19c65beab6e0.png)

Фикс залили в мастер 14.08, релиз 2023.1.1 выпустили 10.08. Ждем нового релиза с обновленным v8-code-style.
