### ISSUE TITLE
Ложное срабатывание проверки: md-object-attribute-comment-incorrect-type

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/v8-code-style#1340]
## Название/код проверки

Код проверки: `md-object-attribute-comment-incorrect-type`

Версия плагина: `Ruby 2023.1.0`

## Пример кода/метаданных содержащих ошибку

![image](https://github.com/1C-Company/v8-code-style/assets/54451084/1224069f-da08-4218-bb9a-c5dee7fc50f1)

## Почему это НЕ ошибка

![image](https://github.com/1C-Company/v8-code-style/assets/54451084/1e91f792-d955-4363-b660-a28cd2118434)

Однако, предлагаю не проверять длину строки комментария. Так как неограниченная строка - это blob на SQL. Приводит к снижению производительности системы. Объекты заметно медленней читаются и записываются. Поэтому иногда стоит указывать Строка(1000) или другую длину. Предлагаю тип строки оставить на усмотрение программиста. Просто проверять, что реквизит Комментарий - это строка.

## Дополнительные материалы

- [Ссылка на стандарт на сайте ИТС](https://its.1c.ru/db/v8std#content:531:hdoc)
- Скриншоты с примерами некорректного состояния кода/метаданных
- Скриншоты с примерами исправленного состояния кода/метаданных

**Comment by DmitryShvaika** [comment]
Извиняюсь - не сразу разобрался. Оказывается ругается не на тип, а на галку "Многострочный режим". Просто 2 проверки сделали как одну. Сэкономили и получилось не очень понятно.

**Comment by VAGoncharov** [comment]
Взял в работу. Диагностические сообщения улучшены.
