### ISSUE TITLE
Добавить оглавление в полезнейшую, но длиннющую статье о типизации

### ISSUE THREAD

**Issue by artbear** [1C-Company/v8-code-style#1344]
## Раздел документации или код проверки
https://github.com/1C-Company/v8-code-style/blob/master/docs/checks/code_typification.md

`1C:Code style V8 -> Инструменты -> Типизация`

## Что необходимо улучшить

Не хватает оглавления, как, например, сделано в ЕДТ

в итоге по длинному файлу неудобно ориентироваться.
приходится постоянно скроллить файл или выполнять поиск множество раз (

## Дополнительные материалы
Пример из ЕДТ 
![image](https://github.com/1C-Company/v8-code-style/assets/2920817/70b09db0-7717-484d-a86a-060ea4fa3e14)

- [Ссылка на стандарт на сайте ИТС](https://its.1c.ru/...)
- Скриншоты с примерами некорректного текста

**Comment by tormozit** [comment]
Ссылка битая

**Comment by potoyalo** [comment]
Жми `Outline` справа наверху и будет тебе оглавление
