### ISSUE TITLE
Проверка module-structure-form-event-regions заставляет перемещать ФункНаСервере() в конец файла.

### ISSUE THREAD

**Issue by Roffild** [1C-Company/v8-code-style#1362]
Проверка module-structure-form-event-regions заставляет перемещать ФункНаСервере() в конец файла.

События генерируются по шаблону рядышком.
```bsl
#Область ОбработчикиКомандФормы

&НаКлиенте
Процедура ПриобретениеТоваров(Команда)
	ПриобретениеТоваровНаСервере();
КонецПроцедуры
//@skip-check module-structure-form-event-regions
&НаСервере
Процедура ПриобретениеТоваровНаСервере()
	// Хочу видеть эту функцию тут, а не на 2023 строк ниже...
КонецПроцедуры

#КонецОбласти
```
Имена функций, которые полностью начинаются с имени события можно игнорировать.

Ruby 2023.1.1

**Comment by marmyshev** [comment]
Правильно заставляет - ровно в этом смысл проверки - требует соблюдать стандарт. https://its.1c.ru/db/v8std#content:455:hdoc

Если Вы не хотите соблюдать этот стандарт в проекте - то можно проверку (как и другие по этому стандарту) отключить в настройках проекта.

Ваше предложение понятно, но сначала его следует внести в стандарт.
