### ISSUE TITLE
Проверки, которые проверяют названия общих модулей, не учитывают постфиксы

### ISSUE THREAD

**Issue by DoublesunRUS** [1C-Company/v8-code-style#14]
Есть стандарт на наименование общих модулей: https://its.1c.ru/db/v8std#content:469:hdoc

Раздел 3.2 содержит список разрешенных постфиксов.

Сейчас проверки на названия общих модулей не учитывают эти постфиксы.

Нужно либо добавлять отдельную настройку, которая будет содержать список разрешенных постфиксов, либо в список суффиксов добавлять суффиксы с постфиксами.
Например
Клиент,Client,КлиентПовтИсп,ClientCached,КлиентПереопределяемый,ClientOverridable

Как идеологически правильно? Расширить список суффиксов или сделать отдельно постфиксы?

**Comment by marmyshev** [comment]
Почитал стандарт еще раз - кажется что "постфикс" это ничего не значащее слово в данном случае: это и не суффикс и не окончание.

Предлагаю, переделать на `"СтрСодержит()"` вместо `"ОканчиваетсяНа()"` как сейчас.

**Comment by DoublesunRUS** [comment]
> Предлагаю, переделать на `"СтрСодержит()"` вместо `"ОканчиваетсяНа()"` как сейчас.

Что делать с модулями
КлиентЛицензирования, КлиентЛицензированияВызовСервера и тому подобным? Добавить условие что содержит не возвращает 0 позицию?

**Comment by NikitaMikhaylovSB** [comment]
Поддержку @DoublesunRUS - на ERP сейчас офигел от количества ложных ошибок...

**Comment by DoublesunRUS** [comment]
@NikitaMikhaylovSB Хочешь меня поддержать, добавь какую-нибудь проверку в этот плагин. :) Потому что эту ошибку я уже поправил, скоро оформлю запрос на слияние.

**Comment by NikitaMikhaylovSB** [comment]
> @NikitaMikhaylovSB Хочешь меня поддержать, добавь какую-нибудь проверку в этот плагин. :) Потому что эту ошибку я уже поправил, скоро оформлю запрос на слияние.
Я могу только хотелки озвучить, а вот вникать в java - не хочу )
