### ISSUE TITLE
В настройках проекта добавить "Поддержка БСП" (по умолчанию настройка включена)

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/v8-code-style#1410]
### Описание проблемы

Не все проекты основаны на БСП и дополнительные проверки функций ЗначенияРеквизитовОбъектов, ЗначениеРеквизитаОбъекта и т.п. не требуются. Отключение опции должно ускорить проверки и дать создавать одноименные функции БСП без привязки к метаданным.

### Описание решения проблемы

В настройках проекта добавить "Поддержка БСП" (по умолчанию настройка включена)
Дать возможность отключать эту настройку, чтобы  использовать только язык платформы 1с.

**Comment by marmyshev** [comment]
Уточните, вы хотите создавать модули которые называются как в БСП, в них методы которые называются как в БСП, но смысл/поведение их другое?

"Выглядит как утка, крякает как утка, пахнет как утка. Но не утка?" (с)

**Comment by DmitryShvaika** [comment]
Мы отказываемся от БСП за ненадобностью. Сейчас используется 2-3 механизма, которые в будущем планируется то же переписать. Просто нет смысла делать лишние проверки и реализацию типов для рефлексных функций БСП. Было бы замечательно иметь возможно отключить этот функционал.

**Comment by marmyshev** [comment]
Это не то о чем спрашивал. 
Приведите пример, когда вы создаете свои функции которые называются как в БСП но имеют другой смысл, другие параметры?

Почему ваши функции, выполняющие другие действия, не как в БСП, вы не называете по другому?

**Comment by DmitryShvaika** [comment]
Я не называю одинаково функции. Речь не об этом. Речь про то, что механизм для рефлексных функций БСП мне не нужен и не используется. Вместо БСП функций сделаны свои, не рефлексные, с другими наименованиями. Думал, проверки быстрее будут работать, если ненужные механизмы отключить.

**Comment by marmyshev** [comment]
Вот! Разобрались, зачем нужно отключение.

Если это единственная причина - то предлагаю закрывать: 
1. Механизм расчета типов функций не добавляет никакой нагрузки, если у вас нет функций с названиями из БСП - ничего не будет загружать процессор.
2. Проверки кода или строгая типизация никак не связаны с механизмом типизации функций БСП.
3. Этот механизм расчета типов используется так же для некоторых платформенных методов, где тип возврата зависит от типа или значения параметров (отражение типов, рефлексия).

**Comment by DmitryShvaika** [comment]
Ок
