### ISSUE TITLE
Убрать поддержку Обычного приложения из стандартов в принципе (не компилировать модули для КлиентОбычнойПриложение)

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/v8-code-style#1412]
### Описание проблемы

Обычное приложение давно нигде не используется и морально устарело. 
Одна из порождаемых проблем описана в задаче
https://github.com/1C-Company/v8-code-style/issues/1411

### Описание решения проблемы

Предлагаю убрать поддержку компиляции модулей в режиме КлиентОбычноеПриложение.
Считать ошибкой, если эта галка установлена на каком-либо модуле (новая проверка)

**Comment by marmyshev** [comment]
Тут не модифицируются сами стандарты. С этим вопросом - нужно писать в форму партнеров.
Как только стандарты обновятся - можно будет переоткрыть.
