### ISSUE TITLE
Сделать подавление ошибок для выделенного фрагмента текста

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/v8-code-style#1413]
### Описание проблемы

Иногда нужно подавить несколько десяткой ошибок. По одной делать это долго.

### Описание решения проблемы

Есть предложение реализовать возможность подавления ошибок во всем выделенном фрагменте текста сразу.

**Comment by marmyshev** [comment]
Такая возможность уже реализована. Можно подавлять:

1. Текущий стейтмет (текущее выражение, текущая строка)
2. Код внутри области (любое количество строк внутри области)
3. Код внутри метода
4. Код внутри методов внутри области
5. Код во всем модуле

Есть команда чтобы обернуть выделенный код в область.

Закрываем?

**Comment by DmitryShvaika** [comment]
шикарно :)
