### ISSUE TITLE
Стандарт 460: Использована конструкция "ДЛЯ ИЗМЕНЕНИЯ".

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#178]
### Название проверки
`Использована конструкция "ДЛЯ ИЗМЕНЕНИЯ".`

**Английское название проверки**
`??`

### Правило анализа кода/метаданных

Подписаться на объект запроса и проверить наличие **ДЛЯ ИЗМЕНЕНИЯ**,  в модели запроса.

### Мета-информация (пожалуйста, заполните если знаете):
- Номер стандарта: `460`
- Код проверки: `??my-check-id`
- Тип ошибки: `ERROR` `SECURITY` `PERFORMANCE`  `WARNING` `PORTABILITY` `LIBRARY_DEVELOPMENT_AND_USAGE` `CODE_STYLE` `UI_STYLE` `SPELLING`
- Критичность: `BLOCKER` `CRITICAL` `MAJOR` `MINOR` `TRIVIAL`
- Код ошибки АПК: `66`

#### Параметры проверки
- NA

#### Текст ошибки
`Использована конструкция "ДЛЯ ИЗМЕНЕНИЯ".`

#### Пример некорректного решения
- NA

#### Описание, почему так делать нельзя

Не следует применять в запросах конструкцию **ДЛЯ ИЗМЕНЕНИЯ**, как не
имеющую смысла в этом режиме (управляемая блокировка).  

#### Пример корректного решения
- NA

#### Дополнительные материалы

- [Использование управляемого режима блокировки](https://its.1c.ru/db/v8std#content:460:hdoc)

**Comment by EightM** [comment]
Заберу себе
