### ISSUE TITLE
Стандарт 488: Новые проверки общих прав

### ISSUE THREAD

**Issue by DoublesunRUS** [1C-Company/v8-code-style#20]
Стандарт разработки https://its.1c.ru/db/v8std#content:488:hdoc в разделах 2 и 3 содержит список ролей для настройки общих прав на корень конфигурации.
Необходимо добавить проверки для всех стандартных ролей.
Каждая проверка будет проверять что указанное в ней право присутствует только в стандартной роли и отсутствует во всех остальных.

**Comment by marmyshev** [comment]
Надо учесть те роли которые уже сделаны в ветке в #12

**Comment by DoublesunRUS** [comment]
Я посмотрел этот пул реквест, в частности файл
https://github.com/1C-Company/v8-code-style/pull/12/files#diff-cfa03ea0e68cc905137f5d5a8c064a7a1eb8220c88c8e5a6f0f8abdb288eedcc

У меня сложилось впечатление что указанный пул реквест не затрагивает раздел 3, а проверяет только ПолныеПрава + те права, которых не должно быть нигде.

То есть если я из этого пул реквеста возьму основную обертку и добавлю свои проверки для раздела 3, то там не будет конфликтов.
