### ISSUE TITLE
Стандарт 689: В функциональной опции не установлен флаг "Привилегированный режим при получении".

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#207]
### Название проверки
`В функциональной опции не установлен флаг "Привилегированный режим при получении".`

**Английское название проверки**
`??`

### Правило анализа кода/метаданных

1.8. Во всех функциональных опциях должны быть выставлены флаги
«Привилегированный режим при получении».

Исключение: в конфигурации могут быть предусмотрены параметризированные
ФО, для которых разработчик специально предусматривает различия в
получаемых значениях пользователями с разными правами.  
Пример: Есть параметризованная ФО
**ИспользватьВалютуПриРасчетеСПерсоналом**, которая параметризуется
организацией. Если пользователь будет получать ее значение в контексте
своих прав, то он не увидит поле «валюта» в документе, если у него нет
ни одной организации, где применяется валютный учет.

### Мета-информация (пожалуйста, заполните если знаете):
- Номер стандарта: `689`
- Код проверки: `??my-check-id`
- Тип ошибки: `ERROR` `SECURITY` `PERFORMANCE`  `WARNING` `PORTABILITY` `LIBRARY_DEVELOPMENT_AND_USAGE` `CODE_STYLE` `UI_STYLE` `SPELLING`
- Критичность: `BLOCKER` `CRITICAL` `MAJOR` `MINOR` `TRIVIAL`
- Код ошибки АПК: `228`

#### Параметры проверки
- NA

#### Текст ошибки
`В функциональной опции не установлен флаг "Привилегированный режим при получении".`

#### Пример некорректного решения
- NA

#### Пример корректного решения
- NA

#### Дополнительные материалы

- [Настройка ролей и прав доступа (Раздел обновлен!)](https://its.1c.ru/db/v8std#content:689:hdoc:1.8)

**Comment by VAGoncharov** [comment]
Взял в работу
