### ISSUE TITLE
Стандарт 737: Использована ролевая настройка видимости для элемента формы.

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#219]
### Название проверки
`Использована ролевая настройка видимости для элемента формы.`

**Английское название проверки**
`??`

### Правило анализа кода/метаданных

Подписаться на элементы формы у которых есть ролевая настройка видимости и проверить что нет настроек.

### Мета-информация (пожалуйста, заполните если знаете):
- Номер стандарта: `737`
- Код проверки: `??my-check-id`
- Тип ошибки: `ERROR` `SECURITY` `PERFORMANCE`  `WARNING` `PORTABILITY` `LIBRARY_DEVELOPMENT_AND_USAGE` `CODE_STYLE` `UI_STYLE` `SPELLING`
- Критичность: `BLOCKER` `CRITICAL` `MAJOR` `MINOR` `TRIVIAL`
- Код ошибки АПК: `341`

#### Параметры проверки
- NA

#### Текст ошибки
`Использована ролевая настройка видимости для элемента формы.`

#### Пример некорректного решения
- NA

#### Описание, почему так делать нельзя

1\. В случае большого количества ролей в конфигурации (от нескольких
десятков) не рекомендуется использовать ролевую настройку видимости в
элементах форм (просмотр и редактирование реквизитов по ролям,
пользовательскую видимость полей формы по ролям, использование команд по
ролям).

#### Пример корректного решения
- NA

#### Дополнительные материалы

- [Проверка прав доступа](https://its.1c.ru/db/v8std#content:737:hdoc:1)

**Comment by marmyshev** [comment]
Связная задача #220

**Comment by marmyshev** [comment]
Связная задача #221

**Comment by VAGoncharov** [comment]
Взял в работу.
