### ISSUE TITLE
Стандарт 644: Устаревшая процедура (функция) расположена вне области "УстаревшиеПроцедурыИФункции".

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#232]
### Название проверки
`Устаревшая процедура (функция) расположена вне области "УстаревшиеПроцедурыИФункции".`

**Английское название проверки**
`??`

### Правило анализа кода/метаданных

При этом устаревшую функцию следует перенести в [область общего
модуля](about:i8100455.htm) **УстаревшиеПроцедурыИФункции**, которая
размещена внутри области **ПрограммныйИнтерфейс**.

### Мета-информация (пожалуйста, заполните если знаете):
- Номер стандарта: `644`
- Код проверки: `??my-check-id`
- Тип ошибки: `ERROR` `SECURITY` `PERFORMANCE`  `WARNING` `PORTABILITY` `LIBRARY_DEVELOPMENT_AND_USAGE` `CODE_STYLE` `UI_STYLE` `SPELLING`
- Критичность: `BLOCKER` `CRITICAL` `MAJOR` `MINOR` `TRIVIAL`
- Код ошибки АПК: `458`

#### Параметры проверки
- NA

#### Текст ошибки
`Устаревшая процедура (функция) расположена вне области "УстаревшиеПроцедурыИФункции".`

#### Пример некорректного решения
- NA

#### Пример корректного решения
- NA

#### Дополнительные материалы

- [Обеспечение совместимости библиотек](https://its.1c.ru/db/v8std#content:644:hdoc:3.1)

**Comment by olgabozhko** [comment]
В работе.
