### ISSUE TITLE
Стандарт 765: Не заполнен заголовок поля динамического списка.

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#244]
### Название проверки
`Не заполнен заголовок поля динамического списка.`

**Английское название проверки**
`??`

### Правило анализа кода/метаданных

3\. Для колонок динамического списка, получающихся в запросе комбинацией
других колонок и имеющих свой псевдоним, необходимо задавать синоним при
разработке. Нельзя опираться на автоматически сгенерированный синоним по
имени/псевдониму.

### Мета-информация (пожалуйста, заполните если знаете):
- Номер стандарта: `765`
- Код проверки: `??my-check-id`
- Тип ошибки: `ERROR` `SECURITY` `PERFORMANCE`  `WARNING` `PORTABILITY` `LIBRARY_DEVELOPMENT_AND_USAGE` `CODE_STYLE` `UI_STYLE` `SPELLING`
- Критичность: `BLOCKER` `CRITICAL` `MAJOR` `MINOR` `TRIVIAL`
- Код ошибки АПК: `464`

#### Параметры проверки
- NA

#### Текст ошибки
`Не заполнен заголовок поля динамического списка.`

#### Пример некорректного решения
- NA

#### Пример корректного решения
- NA

#### Дополнительные материалы

- [Элементы форм: требования по локализации (Раздел обновлен!)](https://its.1c.ru/db/v8std#content:765:hdoc:4)

**Comment by mrshadow300373** [comment]
Есть вопрос. А где писать синоним, если в EDT 2022.1.3 при выборе реквизита динамического списка в палитре свойств никакой реакции. Или это уже проблема EDT?
![изображение](https://user-images.githubusercontent.com/34220218/211207522-f54203fa-7a32-4968-bceb-7602f43fa656.png)
Думал проблема в том, что форма расширена, но в основной конфигурации то же поведение. Палитра свойств не отображается (обновляется) для реквизитов дин списка.

**Comment by vadimeg** [comment]
> Палитра свойств не отображается (обновляется) для реквизитов дин списка.

Это ожидаемое поведение.  В конфигураторе тоже нельзя менять свойства полей дин.списка в редакторе реквизита.
Заголовок для поля можно поменять у элемента формы, который соответствует полю реквизита.

**Comment by mrshadow300373** [comment]
> В конфигураторе тоже нельзя менять свойства полей дин.списка в редакторе реквизита. Заголовок для поля можно поменять у элемента формы, который соответствует полю реквизита.

Да, в конфигураторе то же самое, вопрос о том, что речь идёт о тех полях, которые в элементах формы отсутствуют, но присутствуют в полях динсписка и являются полями, подходящими под условие (у которых автогенерация Поле1, Поле2)
Им то куда синонимы писать? У меня такие есть в запросе, в элементы они не вставлены, в самом запросе все синонимы прописаны.

**Comment by vadimeg** [comment]
> Им то куда синонимы писать?

@marmyshev Скорее всего, проверка должна ругаться только на те поля, которые есть в элементах?
Настройка свойств полей динамического списка через палитру не предусмотрена на уровне реквизита.

**Comment by mrshadow300373** [comment]
Коллеги, каюсь, вопрос снят, предупреждение появляется только для элементов формы, связанных с "сложными полями". И уходит если заполнить синоним у элемента (колонки) таблицы формы. Для реквизитов динамического списка с "сложными полями", но не связанными с элементами формы предупреждение не появляется. Часть элементов была внутри групп колонок, поэтому и создалось впечатление что их нет. Примите извинения что побеспокоил зря. Не работает только подавление. Кроме этого могу только заметить, не очень очевидный способ выявления элементов (колонок таблицы/дерева) форм, для которых нужно заполнить синонимы, так как в предупреждении имени элемента формы не выводится, приходится проверять каждый реквизит наблюдая подсказку к имени элемента (двойная зеленая стрелка вниз) в палитре свойств.
