### ISSUE TITLE
Стандарт 404: Использован метод "ПолучитьФорму()".

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#260]
### Название проверки
`Использован метод "ПолучитьФорму()".`

**Английское название проверки**
`??`

### Правило анализа кода/метаданных

Открытие форм [открытие-форм]
=============

1.1. Для открытия форм следует применять методы глобального
контекста **ОткрытьФорму** или **ОткрытьФормуМодально**.
Применение альтернативного способа, с получением формы и ее последующим
открытием с помощью метода **ПолучитьФорму**, не рекомендуется.
Исключения из этого правила возможны только в особых случаях (см. раздел
ниже «Особые случаи использования форм»).  
  
Рекомендация обусловлена соображениями 

-   повышения устойчивости кода, работающего с формой, за счет
    разделения программного интерфейса для работы с формой и деталей ее
    внутренней реализации,
-   а также сохранения единой стилистики кода прикладных решений.

Кроме того, применение глобальных
методов **ОткрытьФорму** и **ОткрытьФормуМодально** гарантирует
выполнение инициализации формы на сервере в
обработчике **ПриСозданииНаСервере**. Этот подход помогает сосредоточить
весь код инициализации формы в одном месте и исключает "случайное"
обращение к серверу, связанное с инициализацией формы, между строками
кода

Форма = ПолучитьФорму(...)

и

Форма.ОткрытьФорму(...)

> *См. также: раздел «Открытие управляемой формы» статьи *[*«Минимизация
> количества серверных
> вызовов»*](http://vsrv70n/v8std/ru_RU/i8100487.htm)

1.2. В случаях когда форма требует параметризации при открытии, все ее
параметры следует указывать в наборе параметров формы. Таким образом,
набор параметров формы декларативно описывает возможности формы по ее
параметризации.

Параметры формы из этого набора могут быть указаны в вызывающем коде при
получении формы (**ПолучитьФорму**) или при открытии
(**ОткрытьФорму**,**ОткрытьФормуМодально**).

1.3. Не следует применять другие способы параметризации формы при
открытии. Например, нужно избегать обращения к методам и свойствам формы
после ее открытия.   
Например, вместо

МояФорма = Форма.ОткрытьФорму("ОбщаяФорма.ПутеводительПоСистеме");  
МояФорма.Элементы.ГруппаШаг.ТекущаяСтраница =
МойФорма.Элементы.ГруппаШаг.Страницы.Приветствие;

следует по той же причине использовать параметры формы:

Форма.ОткрытьФорму("ОбщаяФорма.ПутеводительПоСистеме", Новый
Структура("РежимОткрытия", "Приветствие"));

1.4 Для получения результата работы формы, открытой модально, вместо
непосредственного обращения к элементам и реквизитам формы

ФормаВопроса = ПолучитьФорму("ОбщаяФорма.ФормаВопроса");  
ФормаВопроса.ОткрытьМодально();  
Если ФормаВопроса.БольшеНеПоказыватьНапоминание Тогда  
// …

следует использовать возвращаемое значение функции **ОткрытьМодально**:

БольшеНеПоказыватьНапоминание =
ФормаВопроса.ОткрытьФормуМодально("ОбщаяФорма.ФормаВопроса");  
Если БольшеНеПоказыватьНапоминание Тогда  
// …

Возвращаемое значение формы формируется в коде модуля формы с помощью
метода формы **Закрыть**.

Исключение могут составлять случаи, когда код вызываемой формы не может
быть переписан с использованием метода формы **Закрыть** по
технологическим соображениям. Например, когда программно открывается
форма элемента, в которой размещена стандартная команда **Записать и
закрыть**.

> *См. также: *[*Ограничения на использование экспортных процедур и
> функций*](about:i8100544.htm)

1.5. Другие ограничения:

-   Обработчик события формы **ПриОткрытии** не должен содержать код по
    открытию какой-либо другой формы вместо открываемой.
-   Не рекомендуется выполнять программное открытие и закрытие формы в
    одном обработчике. Такие действия должны быть разнесены по времени.
    Например, закрытие формы можно выполнять в обработчике ожидания.

Открытие форм объектов с помощью команды меню "Все функции" [открытие-форм-объектов-с-помощью-команды-меню-все-функции]
-----------------------------------------------------------

2.1 Следующие виды форм должны быть всегда доступны пользователю в
режиме **1С:Предприятия** из меню "Все функции" вне зависимости от
того, размещены ли соответствующие объекты в командном интерфейсе
приложения или нет:

-   основная форма списка (для всех объектов)

-   основная форма обработки

-   основная форма отчета

### Мета-информация (пожалуйста, заполните если знаете):
- Номер стандарта: `404`
- Код проверки: `??my-check-id`
- Тип ошибки: `ERROR` `SECURITY` `PERFORMANCE`  `WARNING` `PORTABILITY` `LIBRARY_DEVELOPMENT_AND_USAGE` `CODE_STYLE` `UI_STYLE` `SPELLING`
- Критичность: `BLOCKER` `CRITICAL` `MAJOR` `MINOR` `TRIVIAL`
- Код ошибки АПК: `65`

#### Параметры проверки
- NA

#### Текст ошибки
`Использован метод "ПолучитьФорму()".`

#### Пример некорректного решения
- NA

#### Пример корректного решения
- NA

#### Дополнительные материалы

- [Открытие форм](https://its.1c.ru/db/v8std#content:404:hdoc:1)

**Comment by RedMammoth** [comment]
Взял в работу
