### ISSUE TITLE
Стандарт 702: У реквизита "Ссылка" динамического списка выключен признак "Использовать всегда".

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#266]
### Название проверки
`У реквизита "Ссылка" динамического списка выключен признак "Использовать всегда".`

**Английское название проверки**
`??`

### Правило анализа кода/метаданных

Подписаться наквизит формы и проверить что тип реквизита "Динамический список" если содержит выбираемые поля "Ссылка, Ref" - проверить наличие в секции "использовать всегда".

### Мета-информация (пожалуйста, заполните если знаете):
- Номер стандарта: `702`
- Код проверки: `??my-check-id`
- Тип ошибки: `ERROR` `SECURITY` `PERFORMANCE`  `WARNING` `PORTABILITY` `LIBRARY_DEVELOPMENT_AND_USAGE` `CODE_STYLE` `UI_STYLE` `SPELLING`
- Критичность: `BLOCKER` `CRITICAL` `MAJOR` `MINOR` `TRIVIAL`
- Код ошибки АПК: `160`

#### Параметры проверки
- NA

#### Текст ошибки
`У реквизита "Ссылка" динамического списка выключен признак "Использовать всегда".`

#### Пример некорректного решения
- NA

#### Описание, почему так делать нельзя

Используя возможности управляемых форм, пользователь может добавить
отображение любых реквизитов объектов в динамическом списке. Для того
чтобы пользователь смог воспользоваться этой возможностью, рекомендуется
добавлять в список поле **Ссылка**, у которого нужно отключать
пользовательскую видимость.

Кроме того, при использовании в объектах различных механизмов платформы
1С:Предприятие и **Библиотеку стандартных подсистем**) наличие реквизита
Ссылка в динамических списках может быть критичным для работоспособности
этих механизмов. Например:

-   при использовании механизма характеристик платформы 1С:Предприятие
    (или подсистемы "Свойства" **Библиотеки стандартных подсистем**) в
    динамические списки рекомендуется всегда выводить
    реквизит **Ссылка**, т.к. характеристики (дополнительные реквизиты и
    сведения) можно вывести в колонки списка только используя настройку
    в пользовательском режиме;
-   при разработке команд печати (подсистема "Печать" **Библиотеки
    стандартных подсистем**) реквизит **Ссылка** с
    признаком **"Использовать всегда"** становится обязательным
    для корректной работы этих команд.

#### Пример корректного решения
- NA

#### Дополнительные материалы

- [Реквизит Ссылка в динамических списках](https://its.1c.ru/db/v8std#content:702:hdoc:2.2)

**Comment by olgabozhko** [comment]
В работе.
