### ISSUE TITLE
Стандарт acc_21: Не установлен признак переключения для интерфейса.

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#274]
### Название проверки
`Не установлен признак переключения для интерфейса.`

**Английское название проверки**
`??`

### Правило анализа кода/метаданных

Для отображения общих для всех переключаемых прикладных интерфейсов
пунктов меню и панелей инструментов в конфигурации создается
интерфейс **Общий**. У него снимается признак **Переключаемый.** У
остальных интерфейсов признак "Переключаемый" устанавливается.

### Мета-информация (пожалуйста, заполните если знаете):
- Номер стандарта: `acc_21`
- Код проверки: `??my-check-id`
- Тип ошибки: `ERROR` `SECURITY` `PERFORMANCE`  `WARNING` `PORTABILITY` `LIBRARY_DEVELOPMENT_AND_USAGE` `CODE_STYLE` `UI_STYLE` `SPELLING`
- Критичность: `BLOCKER` `CRITICAL` `MAJOR` `MINOR` `TRIVIAL`
- Код ошибки АПК: `793`

#### Параметры проверки
- NA

#### Текст ошибки
`Не установлен признак переключения для интерфейса.`

#### Пример некорректного решения
- NA

#### Описание, почему так делать нельзя

Интерфейс ""Общий"" не должен переключаться, необходимо снять признак переключения.

#### Пример корректного решения
- NA

#### Дополнительные материалы

- [2.4.5.1. В каждой конфигурации обязательно должны присутствовать интерфейсы "Общий" и "Полный"]()
- [Общие интерфейсы](https://its.1c.ru/db/v8std#content:501:hdoc:1)

**Comment by NikitaMikhaylovSB** [comment]
@marmyshev а это точно нужно делать? Это же для ОФ
