### ISSUE TITLE
Стандарт 467: Избыточное обращение внутри модуля через его имя или псевдоним ЭтотОбъект (к методу, свойству или реквизиту).

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#310]
### Название проверки
`Избыточное обращение внутри модуля через его имя или псевдоним ЭтотОбъект (к методу, свойству или реквизиту).`

**Английское название проверки**
`??`

### Правило анализа кода/метаданных

Правило проверяет обращение к свойствам и методам объектов при обращении
через "ЭтотОбъект." (для модулей объектов и форм) и "ЭтаФорма." (для
модулей форм).  
Также считается избыточным вызов методов из того же модуля при обращении
к методу по имени модуля, кроме модулей с постфиксом "ПовтИсп".

При нахождении подобного обращения регистрируется ошибка.

### Мета-информация (пожалуйста, заполните если знаете):
- Номер стандарта: `467`
- Код проверки: `??my-check-id`
- Тип ошибки: `ERROR` `SECURITY` `PERFORMANCE`  `WARNING` `PORTABILITY` `LIBRARY_DEVELOPMENT_AND_USAGE` `CODE_STYLE` `UI_STYLE` `SPELLING`
- Критичность: `BLOCKER` `CRITICAL` `MAJOR` `MINOR` `TRIVIAL`
- Код ошибки АПК: `531`

#### Параметры проверки
- NA

#### Текст ошибки
`Избыточное обращение внутри модуля через его имя или псевдоним ЭтотОбъект (к методу, свойству или реквизиту).`

#### Пример некорректного решения
- NA

#### Пример корректного решения
- NA

#### Дополнительные материалы

- [Общие требования к конфигурации](https://its.1c.ru/db/v8std#content:467:hdoc)

**Comment by mgalios** [comment]
Работаю над задачей
