### ISSUE TITLE
Стандарт acc_28: Наименование объекта расширения не содержит префикса, соответствующего префиксу самого расширения.

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#324]
### Название проверки
`Наименование объекта расширения не содержит префикса, соответствующего префиксу самого расширения.`

**Английское название проверки**
`??`

### Правило анализа кода/метаданных

8.5. Все добавленные объекты (методы и объекты, отчеты, обработки и
подсистемы, а также обработчики событий) расширения, а также имена
собственных методов и переменных расширяющих модулей, должны иметь
префикс, соответствующий префиксу самого расширения.

Данное правило проверки проверяет, что все собственные объекты
расширения верхнего уровня должны иметь префикс расширения.

8.5. Все добавленные объекты (методы и объекты, отчеты, обработки и
подсистемы, а также обработчики событий) расширения, а также имена
собственных методов и переменных расширяющих модулей, должны иметь
префикс, соответствующий префиксу самого расширения.

Данное правило проверки проверяет, что все собственные объекты
расширения, подчиненные другим объектам, должны иметь префикс
расширения.

### Мета-информация (пожалуйста, заполните если знаете):
- Номер стандарта: `acc_28`
- Код проверки: `??my-check-id`
- Тип ошибки: `ERROR` `SECURITY` `PERFORMANCE`  `WARNING` `PORTABILITY` `LIBRARY_DEVELOPMENT_AND_USAGE` `CODE_STYLE` `UI_STYLE` `SPELLING`
- Критичность: `BLOCKER` `CRITICAL` `MAJOR` `MINOR` `TRIVIAL`
- Код ошибки АПК: `1310`

#### Параметры проверки
- NA

#### Текст ошибки
`Наименование объекта расширения не содержит префикса, соответствующего префиксу самого расширения.`

#### Пример некорректного решения
- NA

#### Пример корректного решения
- NA

#### Дополнительные материалы

- [8.5. Все добавленные объекты (методы и объекты, отчеты, обработки и подсистемы, а также обработчики событий) расширения]()

**Comment by Jimmo910** [comment]
Ссылка в Доп материалах, ведет на эту же страницу... хотелось бы куда нибудь на ИТС
