### ISSUE TITLE
Стандарт 456: Неэкспортная переменная не используется в модуле.

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#369]
### Название проверки
`Неэкспортная переменная не используется в модуле.`

**Английское название проверки**
`??`

### Правило анализа кода/метаданных

В модуле не должно быть неиспользуемых локальных (неэкспортных)
переменных.

### Мета-информация (пожалуйста, заполните если знаете):
- Номер стандарта: `456`
- Код проверки: `module-unused-local-variable`
- Тип ошибки: `ERROR` `SECURITY` `PERFORMANCE`  `WARNING` `PORTABILITY` `LIBRARY_DEVELOPMENT_AND_USAGE` `CODE_STYLE` `UI_STYLE` `SPELLING`
- Критичность: `BLOCKER` `CRITICAL` `MAJOR` `MINOR` `TRIVIAL`
- Код ошибки АПК: `433`

#### Параметры проверки
- NA

#### Текст ошибки
`Неэкспортная переменная не используется в модуле.`

#### Пример некорректного решения
- NA

#### Пример корректного решения
- NA

#### Дополнительные материалы

- [Тексты модулей (Раздел обновлен!)](https://its.1c.ru/db/v8std#content:456:hdoc:2)

**Comment by DoublesunRUS** [comment]
Такое уже в какой-то мере умеет проверять EDT.
