### ISSUE TITLE
Стандарт 712: Длина названия раздела превышает 35 символов

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#37]
**Название проверки**
Длина названия раздела превышает 35 символов

**Английское название проверки**
Section name is more then 35 characters long

**Правило анализа кода/метаданных**

Необходимо проверять подсистемы только верхнего уровня, у которых включен флаг отображения в интерфейсе, синоним подсистемы не должен превышать 35 символов на любом языке.

**Мета-информация (пожалуйста, заполните если знаете):**
- Номер стандарта: 712
- Код проверки: subsystem-synonym-too-long
- Тип ошибки: UI_STYLE
- Критичность:  MINOR
- Код ошибки АПК: 311

**Параметры проверки**
Длина синонима раздела, значение по умолчанию 35.

**Текст ошибки**
Дина названия раздела 48 превышает 35 символов.

**Пример некорректного решения**
- NA

**Описание, почему так делать нельзя**

2.1. Общая длина названия раздела не должна превышать 35 знаков с учетом пробелов (это позволяет разместить название в 2 строки, при дальнейшем увеличении количества знаков появится многоточие). Лучше выбирать названия примерно одного размеры по ширине, чтобы они смотрелись единообразно и ровно.

**Пример корректного решения**
- NA

**Дополнительные материалы**
- Ссылка на стандарт на сайте ИТС https://its.1c.ru/db/v8std#content:712:hdoc

**Comment by disant1** [comment]
Взял в работу
