### ISSUE TITLE
Стандарт 402: Периодичность выполнения регламентного задания меньше одной минуты

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#38]
Пожалуйста, в начале, [прочитайте соглашения по проверкам](https://github.com/1C-Company/v8-code-style/blob/master/Check_Convention.md).

**Название проверки**
Периодичность выполнения регламентного задания меньше одной минуты.

**Английское название проверки**
The periodicity of execution a scheduled job is less than one minute.

**Правило анализа кода/метаданных**
Каждое регламентное задание, у которого задано расписание должно иметь периодичность более 1 минуты.

**Мета-информация (пожалуйста, заполните если знаете):**
- Номер стандарта: 402
- Код проверки: scheduled-job-periodicity-too-short
- Тип ошибки: PERFORMANCE
- Критичность: MAJOR
- Код ошибки АПК: 319

**Параметры проверки**
- NA

**Текст ошибки**
Периодичность выполнения регламентного задания меньше одной минуты.

**Пример некорректного решения**
- NA

**Описание, почему так делать нельзя**

При разработке регламентных заданий необходимо выбирать время и интервал
запуска, исходя из прикладного назначения регламентных заданий, а также
руководствуясь соображением, что частое выполнение регламентных заданий
может негативно влиять на производительность сервера приложений
1С:Предприятие:

- регламентное задание не должно выполняться чаще, чем это нужно с
прикладной точки зрения;
- с точки зрения оптимальной загрузки сервера приложений для
большинства регламентных заданий нормальным является интервал
выполнения заданий в 1 день; 
- исключения могут составлять случаи, когда критичным является частое
выполнение заданий с прикладной точки зрения, например, для
поддержания актуальности данных за короткий период;
- ни в каких случаях не следует задавать периодичность выполнения
регламентных заданий меньше одной минуты;
- периодичность выполнения частых (с периодичностью менее одного дня)
регламентных заданий должна быть сбалансирована со временем
выполнения задания: например, если типичное время выполнения 20
секунд, то периодичность раз в минуту, скорее всего, избыточна;
- выполнение ресурсоемких регламентных операций необходимо по
возможности переносить на время минимальной загрузки сервера
приложений 1С:Предприятие. Например, в нерабочее время или на
выходные дни;
- несколько различных ресурсоемких регламентных заданий лучше
"разносить" по времени, исходя из ожидаемого времени их выполнения.

**Пример корректного решения**
- NA

**Дополнительные материалы**
- Ссылка на стандарт на сайте ИТС https://its.1c.ru/db/v8std#content:402:hdoc
- https://its.1c.ru/db/v8std#content:540:hdoc
- https://its.1c.ru/db/v8std#content:539:hdoc

**Comment by nguninb** [comment]
Прочитать соглашения о проверках не получится, так как ссылка ведет в никуда. Просьба поправить.
