### ISSUE TITLE
Стандарт 439: Использована директива компиляции.

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#390]
### Название проверки
`Использована директива компиляции.`

**Английское название проверки**
`??`

### Правило анализа кода/метаданных

Директивы компиляции:

&НаКлиенте (&AtClient)  
&НаСервере (&AtServer)  
&НаСервереБезКонтекста (&AtServerNoContext)

следует применять только в коде модулей управляемых форм и в коде
модулей команд. В остальных модулях рекомендуется применять инструкции
препроцессору.

### Мета-информация (пожалуйста, заполните если знаете):
- Номер стандарта: `439`
- Код проверки: `form-module-pragma`
- Тип ошибки: `ERROR`
- Критичность: `MAJOR`
- Код ошибки АПК: `104`

#### Параметры проверки
- NA

#### Текст ошибки
`Использована директива компиляции.`

#### Пример некорректного решения
- NA

#### Пример корректного решения
- NA

#### Дополнительные материалы

- [Использование директив компиляции и инструкций препроцессора](https://its.1c.ru/db/v8std#content:439:hdoc:1)

**Comment by DoublesunRUS** [comment]
Такое по крайней мере частично умеет ловить EDT. Необходимо из неё забирать эту проверку.
