### ISSUE TITLE
Стандарт 499: Конструкция "Попытка...Исключение...КонецПопытки" не содержит кода в исключении.

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#394]
### Название проверки
`Конструкция "Попытка...Исключение...КонецПопытки" не содержит кода в исключении.`

**Английское название проверки**
`??`

### Правило анализа кода/метаданных

Необходимо в коде проверки подписаться на объект модели `com._1c.g5.v8.dt.bsl.model.TryExceptStatement` и проверить что в исключениях нет кода (логических элементов)

### Мета-информация (пожалуйста, заполните если знаете):
- Номер стандарта: `499`
- Код проверки: `??my-check-id`
- Тип ошибки:  `WARNING`  `CODE_STYLE`
- Критичность:  `MINOR` `TRIVIAL`
- Код ошибки АПК: `312`

#### Параметры проверки
- Возможно, следует добавить параметр учета комментариев в исключении, которые описывают почему там нет кода

```bsl
Попытка  
// код, приводящий к вызову исключения  
....  
Исключение
   // Здесь не требуется ничего логировать или реагировать - потому что...
КонецПопытки;
```

#### Текст ошибки
`Конструкция "Попытка...Исключение...КонецПопытки" не содержит кода в исключении.`

#### Пример некорректного решения

```bsl
Попытка  
// код, приводящий к вызову исключения  
....  
Исключение // перехват любых исключений  
КонецПопытки;
```

#### Описание, почему так делать нельзя

Недопустимо перехватывать любые исключения, бесследно для системного
администратора.

Как правило, подобная конструкция скрывает реальную проблему, которую
впоследствие невозможно диагностировать.  

#### Пример корректного решения

```bsl
Попытка  
// код, приводящий к вызову исключения  
....  
Исключение  
// Пояснение причин перехвата всех исключений "незаметно" от пользователя.  
// ....  
// И запись события в журнал регистрации для системного администратора.  
ЗаписьЖурналаРегистрации(НСтр("ru = 'Выполнение операции'"),  
    УровеньЖурналаРегистрации.Ошибка,,,  
    ПодробноеПредставлениеОшибки(ИнформацияОбОшибке()));  
КонецПопытки;

```

#### Дополнительные материалы

- [Перехват исключений в коде](https://its.1c.ru/db/v8std#content:499:hdoc:2)

**Comment by EightM** [comment]
Заберу себе, как из черновика выйдет

**Comment by EightM** [comment]
Создание параметра который позволяет не создавать ошибку при наличии поясняющего комментария в блоке исключением выглядит нецелесообразным. 

Во-первых, нельзя проверить, что комментарий содержит действительно полезную информацию, а не является простой заглушкой типа `// ...` или банально закомментированным кодом.

Во-вторых, включение такого параметра вызывает соблазн не писать корректный блок исключения (например добавлять запись в ЖР), а просто писать комментарии для будущего расследования `// Если выпало исключение ошибка будет там-то`

В-третьих, для этой цели может служить локальное подавление проверки. Такой вариант выглядит более предпочтительным, так как подавление проверки будет работать точечно, и зачастую сопровождаться поясняющим комментарием, чтобы такой код мог пройти код ревью.

В целом, можно сделать вывод, что наличие такого параметра приведет скорее к поощрению написания плохого кода, чем к его улучшению

**Comment by marmyshev** [comment]
Было бы классно, в доке для пользователей привести пример как правильно указывать подавление проверки (естественно с комментами):

```bsl
// @skip-check this-check-try-exception - не отлавливаем исключение потому что...
Попытка
  ... 
Исключение
КонецПопытки;
```
