### ISSUE TITLE
Стандарт 783: Нарушена схема работы с транзакциями: преждевременный выход из блока "Попытка..Исключение" без завершения или отмены транзакции.

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#395]
### Название проверки
`Нарушена схема работы с транзакциями: преждевременный выход из блока "Попытка..Исключение" без завершения или отмены транзакции.`

**Английское название проверки**
`??`

### Правило анализа кода/метаданных

3.6. При использовании [транзакций](about:i8100648.htm) следует
придерживаться следующей схемы обработки исключений в коде на сервере:

// 1. Начало транзакции  
НачатьТранзакцию();  
Попытка  
// 2. Вся логика блокировки и обработки данных размещается в блоке
Попытка-Исключение  
Запрос = Новый Запрос("...");  
Выборка = Запрос.Выполнить().Выбрать();  
Пока Выборка.Следующий() Цикл  
...  
КонецЦикла;  
  
// 3. В самом конце обработки данных выполняется попытка зафиксировать
транзакцию  
ЗафиксироватьТранзакцию();  
Исключение  
// 4. В случае любых проблем с СУБД, транзакция сначала отменяется...  
ОтменитьТранзакцию();  
// 5. ...затем проблема фиксируется в журнале регистрации...  
ЗаписьЖурналаРегистрации(НСтр("ru = 'Выполнение операции'"),
УровеньЖурналаРегистрации.Ошибка,,,
ПодробноеПредставлениеОшибки(ИнформацияОбОшибке()));  
// 6. ... после чего, проблема передается дальше вызывающему коду.  
ВызватьИсключение;  
КонецПопытки;

Поскольку исключение не отменяет транзакцию сразу, но запрещает успешное
завершение транзакции, то все вызовы **НачатьТранзакцию**, с одной
стороны, и **ЗафиксироватьТранзакцию** или **ОтменитьТранзакцию**, с
другой стороны, должны быть парными.

Отсутствие обработки исключительных ситуаций приводит к зависшим
транзакциям и к сложнодиагностируемым ошибкам вида «В этой транзакции
уже происходили ошибки» в произвольных местах кода. При этом в случае
вложенных операторов **НачатьТранзакцию**, следует обеспечить вызов всех
парных операторов **ОтменитьТранзакцию**. Для этого в конце блока
**Исключение** необходимо пробросить исключение выше по стеку с помощью
**ВызватьИсключение** (как в примере выше) и соответствующим образом
обработать исключение на каждом уровне стека.

### Мета-информация (пожалуйста, заполните если знаете):
- Номер стандарта: `783`
- Код проверки: `??my-check-id`
- Тип ошибки: `ERROR` `SECURITY` `PERFORMANCE`  `WARNING` `PORTABILITY` `LIBRARY_DEVELOPMENT_AND_USAGE` `CODE_STYLE` `UI_STYLE` `SPELLING`
- Критичность: `BLOCKER` `CRITICAL` `MAJOR` `MINOR` `TRIVIAL`
- Код ошибки АПК: `521`

#### Параметры проверки
- NA

#### Текст ошибки
`Нарушена схема работы с транзакциями: преждевременный выход из блока "Попытка..Исключение" без завершения или отмены транзакции.`

#### Пример некорректного решения
- NA

#### Пример корректного решения
- NA

#### Дополнительные материалы

- [Транзакции: правила использования (Новый раздел!)](https://its.1c.ru/db/v8std#content:783:hdoc:1.3)

**Comment by iArtemv** [comment]
функциональность покрывается задачами #564 и #565
