### ISSUE TITLE
Стандарт 547: Использован оператор "Перейти".

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#398]
### Название проверки
`Использован оператор "Перейти".`

**Английское название проверки**
`??`

### Правило анализа кода/метаданных

Подписаться на наличие объекта GoTo и выдать ошибку
 

### Мета-информация (пожалуйста, заполните если знаете):
- Номер стандарта: `547`
- Код проверки: `??my-check-id`
- Тип ошибки:   `WARNING` `CODE_STYLE` 
- Критичность: `MAJOR` `MINOR` `TRIVIAL`
- Код ошибки АПК: `89`

#### Параметры проверки
- NA

#### Текст ошибки
`Использован оператор "Перейти".`

#### Пример некорректного решения
- NA

#### Пример корректного решения
- NA

#### Дополнительные материалы

- [Ограничение на использование оператора Перейти](https://its.1c.ru/db/v8std#content:547:hdoc:1)

**Comment by VAGoncharov** [comment]
Взял в работу.
