### ISSUE TITLE
2021.2.3+0.1.0.109: Правильно диагностирует проблему, но неверное подставляет что за проблема

### ISSUE THREAD

**Issue by NikitaMikhaylovSB** [1C-Company/v8-code-style#42]
Подключен плагин к ERP 2.5.7.150
Проверка нашла неиспользуемый метод (подключается программно), но в окне ошибок показывает иное правило диагности (вместо неиспользуемого метода - превышение количества ключей в структуре)

**Как воспроизвести**
Шаги для воспроизведения ошибки:
1. Установите EDT 2021.2.3
2. Установите плагин 0.1.0.109
3. Импортируйте ERP 2.5.7.150
4. В списке ошибок найдите любую ошибку с диагностикой "Неиспользуемый метод..."
5. Код проверки будет от проверки иного типа

**Ожидаемое поведение**
Правильный тип проверки

**Скриншоты**
![изображение](https://user-images.githubusercontent.com/37539066/130268947-b7524ecd-102c-483d-a249-40551a98ebb9.png)

**Comment by marmyshev** [comment]
Разработчики подтвердили - это ошибка EDT.
