### ISSUE TITLE
Стандарт 689: В документе, предполагающем проведение, не установлен флаг "Привилегированный режим при отмене проведения".

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#420]
### Название проверки
`В документе, предполагающем проведение, не установлен флаг "Привилегированный режим при отмене проведения".`

**Английское название проверки**
`??`

### Правило анализа кода/метаданных

Подписаться на документы, проверить флаг привилегированного режима отмены проведения, проверить наличие регистров при проведении

### Мета-информация (пожалуйста, заполните если знаете):
- Номер стандарта: `689`
- Код проверки: `??my-check-id`
- Тип ошибки: `ERROR``PERFORMANCE`  `WARNING` `PORTABILITY` `CODE_STYLE`
- Критичность: `BLOCKER` `CRITICAL` `MAJOR` `MINOR` `TRIVIAL`
- Код ошибки АПК: `227`

#### Параметры проверки
- NA

#### Текст ошибки
`В документе, предполагающем проведение, не установлен флаг "Привилегированный режим при отмене проведения".`

#### Пример некорректного решения
- NA

#### Описание, почему так делать нельзя

1.7. Во всех документах, предполагающих проведение, должны быть
выставлены флаги «Привилегированный режим при проведении» и
«Привилегированный режим при отмене проведения», поэтому не нужно
создавать роли, дающие права на изменение регистров, подчиненных
регистраторам.

Исключение: документы, предназначенные для непосредственной
корректировки записей регистров, могут проводиться с проверкой прав
доступа, но в этом случае необходимо предусмотреть роли, дающие права на
изменение регистров.

 

#### Пример корректного решения
- NA

#### Дополнительные материалы

- [Настройка ролей и прав доступа (Раздел обновлен!)](https://its.1c.ru/db/v8std#content:689:hdoc:1.7)

**Comment by nguninb** [comment]
Первая часть "Привилегированный режим при проведении" это другой issue?

**Comment by VAGoncharov** [comment]
Взял в работу.

**Comment by VAGoncharov** [comment]
@marmyshev #525 закрыт после мержа, этот ишуз тоже можно закрывать.
