### ISSUE TITLE
Стандарт 767: Задано наименование предопределенного регламентного задания.

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#431]
### Название проверки
`Задано наименование предопределенного регламентного задания.`

**Английское название проверки**
`??`

### Правило анализа кода/метаданных

Проверить что имя регламентного задания пустое.

### Мета-информация (пожалуйста, заполните если знаете):
- Номер стандарта: `767`
- Код проверки: `??my-check-id`
- Тип ошибки: `ERROR` `SECURITY` `PERFORMANCE`  `WARNING` `PORTABILITY` `LIBRARY_DEVELOPMENT_AND_USAGE` `CODE_STYLE` `UI_STYLE` `SPELLING`
- Критичность: `BLOCKER` `CRITICAL` `MAJOR` `MINOR` `TRIVIAL`
- Код ошибки АПК: `449`

#### Параметры проверки
- NA

#### Текст ошибки
`Задано наименование предопределенного регламентного задания.`

#### Пример некорректного решения
- NA

#### Описание, почему так делать нельзя

1\. Предопределенным регламентным заданиям не следует задавать
наименования в конфигураторе. Вместо этого, достаточно задать синоним
предопределенного регламентного задания.

#### Пример корректного решения
- NA

#### Дополнительные материалы

- [Регламентные задания: требования по локализации](https://its.1c.ru/db/v8std#content:767:hdoc:1)

**Comment by kuzja086** [comment]
Взял для разработки
