### ISSUE TITLE
Проверка ОбменДанными.Загрузка не проверяет расширения

### ISSUE THREAD

**Issue by DoublesunRUS** [1C-Company/v8-code-style#457]
**Опишите ошибку**
Диагностика data-exchange-load
Для методов с аннотациями Перед и После проверка не проверяет отсутствие обмена данными

**Как воспроизвести**
Переопределить процедуру ПередЗаписью в расширении с аннотацией После

**Ожидаемое поведение**
Должно выводиться сообщение об ошибке

**Окружение (пожалуйста укажите информацию):**
 - Версия 1C:Code-Style-V8 0.1.0.114
 - Версия 1C:EDT 2021.2.5

**Comment by marmyshev** [comment]
Достаточно доработать проверку прагмы (`getPragma()`) метода в что там указана процедура события, которое переопределяется.
