### ISSUE TITLE
Стандарт 531: Документ не имеет реквизита "Комментарий".

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#487]
### Название проверки
`Документ не имеет реквизита "Комментарий".`

**Английское название проверки**
`??`

### Правило анализа кода/метаданных

1\. Для всех документов рекомендуется создавать реквизит **Комментарий**
(строка неограниченной длины). В этом реквизите пользователи могут
записывать по документу различные заметки служебного характера, которые
не относятся к прикладной специфике документа (например, причина пометки
на удаления и т.п.). Доступ к реквизиту для пользователей должен быть
настроен также как и к самому документу (если документ доступен только
для чтения, то и комментарий – только для чтения; если же есть право
записи документа, то и значение реквизита также можно изменять).

### Мета-информация (пожалуйста, заполните если знаете):
- Номер стандарта: `531`
- Код проверки: `??my-check-id`
- Тип ошибки: `ERROR` `SECURITY` `PERFORMANCE`  `WARNING` `PORTABILITY` `LIBRARY_DEVELOPMENT_AND_USAGE` `CODE_STYLE` `UI_STYLE` `SPELLING`
- Критичность: `BLOCKER` `CRITICAL` `MAJOR` `MINOR` `TRIVIAL`
- Код ошибки АПК: `108`

#### Параметры проверки
- NA

#### Текст ошибки
`Документ не имеет реквизита "Комментарий".`

#### Пример некорректного решения
- NA

#### Пример корректного решения
- NA

#### Дополнительные материалы

- [Реквизит "Комментарий" у документов](https://its.1c.ru/db/v8std#content:531:hdoc:1)

**Comment by VAGoncharov** [comment]
Взял в работу.
