### ISSUE TITLE
Стандарт acc_2: Обращение к несуществующей роли.

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#546]
### Название проверки
`Обращение к несуществующей роли.`

**Английское название проверки**
`??`

### Правило анализа кода/метаданных

В параметрах функций "РольДоступна" и "Пользователи.РолиДоступны" должны
быть указаны существующие роли.

### Мета-информация (пожалуйста, заполните если знаете):
- Номер стандарта: `acc_2`
- Код проверки: `??my-check-id`
- Тип ошибки: `ERROR` `SECURITY` `PERFORMANCE`  `WARNING` `PORTABILITY` `LIBRARY_DEVELOPMENT_AND_USAGE` `CODE_STYLE` `UI_STYLE` `SPELLING`
- Критичность: `BLOCKER` `CRITICAL` `MAJOR` `MINOR` `TRIVIAL`
- Код ошибки АПК: `283`

#### Параметры проверки
- NA

#### Текст ошибки
`Обращение к несуществующей роли.`

#### Пример некорректного решения
- NA

#### Пример корректного решения
- NA

#### Дополнительные материалы

- [Проверка существования ролей]()

**Comment by VAGoncharov** [comment]
Взял в работу.
