### ISSUE TITLE
Стандарт 467: Некорректно заполнено свойство "Путь к данным" у поля динамического списка.

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#555]
### Название проверки
`Некорректно заполнено свойство "Путь к данным" у поля динамического списка.`

**Английское название проверки**
`??`

### Правило анализа кода/метаданных

2.2. В конфигурации не должно быть неиспользуемых объектов метаданных
(справочников, документов, разделов командного интерфейса и т.п.) и
программного кода (общих модулей, процедур, функций, переменных и т.п.),
который не используется ни в самой конфигурации, ни для интеграции с
другими системами.

...

При ручном изменении запроса динамического списка очищается свойство
"Путь к данным" у его полей на форме. Это приводит к тому, что элемент
формы (колонка таблицы) перестает быть связанным с полем динамического
списка и исчезает из таблицы на форме.

При этом в файлах форм из выгрузки XML значение свойства "Путь к данным"
начинается со знака "\~", например, для поля "Наименование":
"\<DataPath\>\~Список.Description\</DataPath\>".

Аналогичная ситуация для кнопок командной панели, связанных
свойством "Данные" со стандартным полем динамического списка, например,
для кнопки с заполненным значением "Ссылка" в свойстве "Данные":
"\<DataPath\>\~Items.Список.CurrentData.Ссылка\</DataPath\>".

### Мета-информация (пожалуйста, заполните если знаете):
- Номер стандарта: `467`
- Код проверки: `form-item-data-path`
- Тип ошибки: `ERROR` 
- Критичность: `CRITICAL`
- Код ошибки АПК: `524`

#### Параметры проверки
- NA

#### Текст ошибки
`Некорректно заполнено свойство "Путь к данным" у поля динамического списка.`

#### Пример некорректного решения
- NA

#### Пример корректного решения
- NA

#### Дополнительные материалы

- [Общие требования к конфигурации](https://its.1c.ru/db/v8std#content:467:hdoc:2.2)

**Comment by KigBan** [comment]
После загрузки ERP УХ ест ошибка:
Описание	Положение		Код проверки
Свойство "Не установлено "Использовать всегда"" имеет некоректное значение "Список.Остановлен": 2 сегмент "Остановлен" ссылается на неизвестный объект			form-data-path
В описании проверки стоит #std467, поэтому сюда. Хотя найти было не просто. Есть инструкция как искать?
К сути проблемы, в BusinessProcesses\ЗаявкаКабинетСотрудника\Forms\ФормаСписка\Ext\Form.xml описанный случай:
```		<Attribute name="Список" id="1">
			<Type>
				<v8:Type>cfg:DynamicList</v8:Type>
			</Type>
			<MainAttribute>true</MainAttribute>
			<UseAlways>
				<Field>~Список.Остановлен</Field>
				<Field>Список.Завершен</Field>
```
При импорте в EDT он ложиться сюда: src\BusinessProcesses\ЗаявкаКабинетСотрудника\Forms\ФормаСписка\Form.form как
```    <notDefaultUseAlwaysAttributes xsi:type="form:DataPath">
      <segments>Список.Остановлен</segments>
    </notDefaultUseAlwaysAttributes>
```
Мне кажется ошибка в импорте, но пишу сюда, т.к. на него сработало правило.
Заодно поправить слово "некоректное".

**Comment by marmyshev** [comment]
@KigBan зачем вы пишите в закрытую задачу?

У вас несколько не связанных вопросов:
1. что-то не так с импортом - это в чат по ЕДТ
2. битые ссылки в метаданных формы - нужно исправлять (скорее всего удалять) - спрашивайте в чате по ЕДТ
3. опечатка в тексте - зарегайте отдельную ошибку (или даже можете сами поправить - присылайте PR :) 
4. Если проверка неправильно работает - тоже отдельно ошибку регайте
