### ISSUE TITLE
Стандарт 488: Установлено право "Интерактивное удаление".

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#580]
### Название проверки
`Установлено право "Интерактивное удаление".`

**Английское название проверки**
`??`

### Правило анализа кода/метаданных

5\. Ни в одной роли, включая **ПолныеПрава** и **АдминистраторСистемы**,
не должно быть установлено (кроме отдельных обоснованных случаев)
следующих прав:

-   **Право интерактивного удаления**
-   **Интерактивное удаление предопределенных данных**
-   **Интерактивная пометка удаления предопределенных данных**
-   **Интерактивное снятие пометки удаления предопределенных данных**
-   **Интерактивное удаление помеченных предопределенных данных**

### Мета-информация (пожалуйста, заполните если знаете):
- Номер стандарта: `488`
- Код проверки: `right-interactive-delete`
- Тип ошибки: `ERROR` `SECURITY` `PERFORMANCE`  `WARNING` `PORTABILITY` `LIBRARY_DEVELOPMENT_AND_USAGE` `CODE_STYLE` `UI_STYLE` `SPELLING`
- Критичность: `BLOCKER` `CRITICAL` `MAJOR` `MINOR` `TRIVIAL`
- Код ошибки АПК: `1149`

#### Параметры проверки
- NA

#### Текст ошибки
`Установлено право "Интерактивное удаление".`

#### Пример некорректного решения
- NA

#### Описание, почему так делать нельзя

Необходимо снять право  "Интерактивное удаление".

#### Пример корректного решения
- NA

#### Дополнительные материалы

- [Стандартные роли](https://its.1c.ru/db/v8std#content:488:hdoc:5)
- [Использование предопределенных элементов](https://its.1c.ru/db/v8std#content:697:hdoc:1.2)
- [2.6.6. Ни в одной роли, включая ПолныеПрава и АдминистраторСистемы, не должно быть установлено (кроме отдельных обоснованных случаев) следующих прав]()

**Comment by NikitaMikhaylovSB** [comment]
@marmyshev очень хочется увидеть исправление. А то сейчас в плагине указано, что такая проверка есть, а по факту - ее нет.
Это не внушает доверия инструменту (
Нужно или убрать из плагина срочно строку с этой проверкой, или срочно реализовать.

**Comment by marmyshev** [comment]
> А то сейчас в плагине указано, что такая проверка есть, а по факту - ее нет.

По факту есть проверка и она корректно работает для всех случаев, кроме 1 не очевидного случая.

Доверие к инструменту должно быть от того что он делает, а не из-за того что он не делает.
