### ISSUE TITLE
Исключить из проверки "Метод не найден в исходном объекте" проверку методов COM-объектов.

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/v8-code-style#790]
Для COM-объектов невозможно определить список методов, их параметры и возвращаемые значения,
поэтому проверка "Метод не найден в исходном объекте" к ним неприменима.

В тексте модуля с включенной проверкой типов указать любой метод любого COM-объекта, например
_Команда = Новый COMОбъект("ADODB.Command");
Выборка = Команда.Execute();_

Для COM-Объектов проверка "Метод не найден в исходном объекте" не должна выполняться.

![image](https://user-images.githubusercontent.com/54451084/134356452-dc951b19-e263-402f-8799-83db6c112eef.png)

**Окружение (пожалуйста укажите информацию):**
 - OS: Windows
 - Версия 1C:Code-Style-V8 0.1.0.119
 - Версия 1C:EDT Ruby 2021.2.5

**Comment by marmyshev** [comment]
Можно добавить с параметром "Не проверять методы в Ком-объекте"

**Comment by DmitryShvaika** [comment]
Да, будет нормально... В текущих реалиях для каждого COM-объекта получается плагин писать надо?

**Comment by marmyshev** [comment]
Я думаю что можно написать один универсальный плагин который для любых COM-объектов будет получать API компонент...

Если в Windows вообще возможно запрашивать API...

**Comment by DmitryShvaika** [comment]
> Я думаю что можно написать один универсальный плагин который для любых COM-объектов будет получать API компонент...
> 
> Если в Windows вообще возможно запрашивать API...

У COM-объектов для этого как раз есть интерфейс Iknow который возвращает список методов. Вот только список параметров и их типы где брать....

**Comment by marmyshev** [comment]
Предлагаю заводить идею плагина тут https://github.com/marmyshev/edt-plugins/issues и там далее описывать пожелания, что хотелось бы. Может быть кто-то захочет сделать такой плагин?

Тут оставлю мнение, что кмк со стороны EDT есть всё необходимое чтобы сделать поддержку типизации COM-Объектов через плагин - но это будет работать только на Windows машинах разработчиков, либо нужно сохранять декларацию типов/свойств/методов COM-объекта во внешнем файле который будет храниться в проекте или как-то ещё, будет доступен разработчикам на других ОС, валидация кода в CI (в докер, в Linux) тоже могла бы работать корректно.

**Comment by DmitryShvaika** [comment]
Декларации наверное более приемлемый вариант. Так как типы и параметры могут меняться с версией COM-объекта.
