### ISSUE TITLE
Стандарт 794: Запрет синхронных вызовов в режиме использования синхронных вызовов "Не использовать".

### ISSUE THREAD

**Issue by s-d-c2019** [1C-Company/v8-code-style#794]
### Название проверки

`Запрет синхронных вызовов в режиме использования синхронных вызовов "Не использовать".`

**Английское название проверки**

`Prohibit synchronous calls in the "Do not use" synchronous call usage mode.`

### Правило анализа кода/метаданных

Если в свойствах конфигурации установлен режим использования синхронных вызовов в значение "Не использовать" выдавать ошибку для всех синхронных вызов на клиенте.

![image](https://user-images.githubusercontent.com/54451084/134696333-5a71b68f-fd7f-4605-8d6c-a0eb3f66f3d2.png)

### Мета-информация:

- Номер стандарта: `794`
- Код проверки: `prohibit-synchronous-calls`
- Тип ошибки: `ERROR`
- Критичность: `CRITICAL`

### Текст ошибки

Синхронные вызовы запрещены, так как для конфигурации установлен Режим использования синхронных вызовов "Не использовать".

### Пример некорректного решения

`КопироватьФайл("c:\temp\1.txt", "c:\temp\2.txt") ; `

### Описание, почему так делать нельзя

В режиме использования синхронных вызовов "Не использовать" использование синхронного вызова приводит к  ошибке "Использование синхронных методов на клиенте запрещено".

### Пример корректного решения

```
Оповещение = Новый ОписаниеОповещения("КопированиеФайловЗавершено", ЭтаФорма);
НачатьКопированиеФайла(Оповещение, "c:\temp\1.txt", "c:\temp\2.txt") ; 
```

### Дополнительные материалы

- https://its.1c.ru/db/v8std#content:703:hdoc
- https://its.1c.ru/db/metod8dev/content/5293/hdoc

**Comment by marmyshev** [comment]
А откуда такой номер стандарта?

**Comment by marmyshev** [comment]
Дубль #572

**Comment by DmitryShvaika** [comment]
> А откуда такой номер стандарта?

Это номер задачи, извинюсь, думал нумерация как раз по задачам. Потом понял, что у стандартов есть свои номера.
