### ISSUE TITLE
Команда включения строгой типизации по всему проекту или выделенному списку объектов

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#818]
## Описание проблемы

Для желающих оценить строгую типизацию - необходимо проходиться по всем модулям и добавлять аннотацию строгой типизации. Кажется это не удобно, и хочется одним кликом включить.

## Описание решения проблемы

Можно в навигатор добавить контекстную команду, которая в зависимости от списка выбранных объектов будет:
- Если выбраны проекты - для каждого файла `*.bsl` проекта 
- Если выбраны метаданные - для каждого файла `*.bsl` согласно иерархии метаданных 
- Если выбрана подсистема - для каждого модуля каждого объекта состава подсистемы иерархически 
- Если выбраны список файлов/каталогов - для каждого файла `*.bsl` выбранные из списка по иерархии

Добавлять аннотацию если она еще не существует.

Желательно учитывать "Запрет редактирования" по этому объекту. 

## Доплнительная информация

Кажется @DitriXEDT говорил о такой потребности

**Comment by DitriXNew** [comment]
Кейс немного уточню.
Есть конфа, на овер дофига модулей.
И я приступаю к строгой типизации.
Первое что я хочу сделать - проставить везде тег строгой типизации.
Далее - снять все модули, в которых есть ошибки.
Цель: есть куча модулей, в том числе модулей форм, особенно списка, где в целом есть только обработчики событий. Которые, в целом, поддаются легкой типизации, и не нуждаются в описании их в виде комментариев.
И я хочу, чтобы такие модули - сразу фиксировались как модули с контролем типизации.

Поле этого - я хотел бы включать типизацию "сверзу вниз".
Т.е. вначале - включить типизацию в модулях менеджеров объектов, например, вначале в регистрах, потом в планах видов, и так по нарастающей, и закончить справочниками и документами.
Потом включить в модулях объектов, потом в глобальных модулях и т.д.

Цель - включать все поэтапно. Начиная с самых простых кейсов, и заканчивая более сложными.
И сверху вниз, т.е. ситуаций, когда вызываются функции модуля объекта, или менеджера, или модуля формы - не значительны. Поэтому там типизацию включить проще.
А потом, когда прихожу к общему модулю, я хочу чтобы при генерации комментария - ЕДТ сама подставляла типы сверху, кототрые  я уже ранее описал.

**Comment by marmyshev** [comment]
> Первое что я хочу сделать - проставить везде тег строгой типизации.
> Далее - снять все модули, в которых есть ошибки.

Полагаю, что такое можно сделать через Quick-fix  - помечаем все модули, потом везде где есть ошибки - по квикфиксу удаляем аннотации. Нужно отельной задачей про квикфикс.

Остальные сценарии "сверху вниз" - думаю можно реализовать простым отбором в панели ошибок по модулям форм например - и аналогично квикфиксом удалять аннотации.
