### ISSUE TITLE
Стандарт 467: Превышена максимальная длина ресурса регистра накопления или бухгалтерии (25 знаков).

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#84]
### Название проверки
`Превышена максимальная длина ресурса регистра накопления или бухгалтерии (25 знаков).`

**Английское название проверки**
`??`

### Правило анализа кода/метаданных

1.2. Конфигурация должна быть одинаково рассчитана на работу со всеми
СУБД, операционными системами, веб-браузерами и различными режимами
работы, которые поддерживает платформа 1С:Предприятие.

Соблюдение стандартов "Приложение 8. Особенности работы с различными
СУБД"  
<http://its.1c.ru/db/v83doc#bookmark:dev:TI000001285>

8.3. Сервер IBM DB2
-------------------

● Максимальная длина ресурсов регистров накопления и бухгалтерии – 25
знаков (а не 32).

### Мета-информация (пожалуйста, заполните если знаете):
- Номер стандарта: `467`
- Код проверки: `??my-check-id`
- Тип ошибки: `ERROR` `SECURITY` `PERFORMANCE`  `WARNING` `PORTABILITY` `LIBRARY_DEVELOPMENT_AND_USAGE` `CODE_STYLE` `UI_STYLE` `SPELLING`
- Критичность: `BLOCKER` `CRITICAL` `MAJOR` `MINOR` `TRIVIAL`
- Код ошибки АПК: `377`

#### Параметры проверки
- NA

#### Текст ошибки
`Превышена максимальная длина ресурса регистра накопления или бухгалтерии (25 знаков).`

#### Пример некорректного решения
- NA

#### Пример корректного решения
- NA

#### Дополнительные материалы

- [Общие требования к конфигурации](https://its.1c.ru/db/v8std#content:467:hdoc)

**Comment by muhtimur** [comment]
Забыл тут указать)
Работаю над этой задачкой
