### ISSUE TITLE
Стандарт 455: Одина процедура назначена обработчиком событий разным элементам формы

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#855]
### Название проверки

`Одина процедура назначена обработчиком событий разным элементам формы`

**Английское название проверки**

`One procedure is assigned as event handler to different form items`

### Правило анализа кода/метаданных

Подписка на поле Event handler в элементах формы, в том случае, если название процедуре не образовано как "имя элемента" + "имя события" - то для таких процедур искать все элементы на форме и проверять, используется ли процедура где-то ещё. 

Возможно стоит реализовать алгоритм обхода по всей форме с кастомной подпиской на форму, но регистрацию изменений по коллекциям событий элементов формы.

### Мета-информация (пожалуйста, заполните если знаете):

- Номер стандарта: `455`
- Код проверки: `form-items-one-event-handler`
- Тип ошибки: `WARNING`
- Критичность:  `MAJOR` 
- Код ошибки АПК: `--`

### Дополнительные материалы

- [Структура модуля](https://its.1c.ru/db/v8std#content:455:hdoc)

**Comment by RedMammoth** [comment]
Взял

**Comment by marmyshev** [comment]
@RedMammoth как дела с работой по задаче?

**Comment by RedMammoth** [comment]
> @RedMammoth как дела с работой по задаче?

Всё не было времени. Доберусь или в эти выходные или на следующей неделе
