### ISSUE TITLE
Стандарт 455: Одина процедура назначена обработчиком выполнения разным командам формы

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#856]
### Название проверки

`Одина процедура назначена обработчиком выполнения разным командам формы`

**Английское название проверки**

`One procedure is assigned as action handler to different form commands`

### Правило анализа кода/метаданных

Подписка на поле Action handler в командах формы, в том случае, если название процедуре не образовано как "имя команды" + "Команда" - то для таких процедур искать все команды на форме и проверять, используется ли процедура где-то ещё. 

Возможно стоит реализовать алгоритм обхода по всей форме с кастомной подпиской на форму, но регистрацию изменений по коллекциям событий команд формы.

### Мета-информация (пожалуйста, заполните если знаете):

- Номер стандарта: `455`
- Код проверки: `form-commands-one-action-handler`
- Тип ошибки: `WARNING`
- Критичность:  `MAJOR` 
- Код ошибки АПК: `--`

### Дополнительные материалы

- [Структура модуля](https://its.1c.ru/db/v8std#content:455:hdoc)

**Comment by mgalios** [comment]
Работаю над задачей

**Comment by iArtemv** [comment]
@mgalios задачу буду делать в рамках общей #1080
