### ISSUE TITLE
Стандарт 455: Программный вызов обработчика события формы

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#857]
### Название проверки

`Программный вызов обработчика события формы`

**Английское название проверки**

`Program invocation of form event handler`

### Правило анализа кода/метаданных

На этапе запуска необходимо отсеивать модули у которых ModuleType <> FORM_MODULE.

Подписать на Invocation, далее проверить что у вызова методом является StaticFeatureAccess и feature-entry локальная процедура (Procedure).

По процедуре проверить, что она не является обработчиком событий формы (как самой формы, так и элементов формы, аналогично команд формы).

### Мета-информация (пожалуйста, заполните если знаете):

- Номер стандарта: `455`
- Код проверки: `invocation-form-event-handler`
- Тип ошибки: `WARNING`
- Критичность:  `MAJOR` 
- Код ошибки АПК: `--`

### Пример некорректного решения

```bsl
&НаКлиенте
Процедура ПоИсполнителюПриИзменении(Элемент)
 ПараметрыОтбора = Новый Соответствие();
 ПараметрыОтбора.Вставить("ПоАвтору", ПоАвтору);
 ПараметрыОтбора.Вставить("ПоИсполнителю", ПоИсполнителю);
 УстановитьОтборСписка(Список, ПараметрыОтбора);
КонецПроцедуры

&НаКлиенте
Процедура ПоАвторуПриИзменении(Элемент)
 ПоИсполнителюПриИзменении(Неопределено);
КонецПроцедуры
```

### Пример корректного решения

```bsl
&НаКлиенте
Процедура ПоИсполнителюПриИзменении(Элемент)
 УстановитьОтбор();
КонецПроцедуры

&НаКлиенте
Процедура ПоАвторуПриИзменении(Элемент)
 УстановитьОтбор();
КонецПроцедуры

&НаСервере
Процедура УстановитьОтбор()
 ПараметрыОтбора = Новый Соответствие();
 ПараметрыОтбора.Вставить("ПоАвтору", ПоАвтору);
 ПараметрыОтбора.Вставить("ПоИсполнителю", ПоИсполнителю);
 УстановитьОтборСписка(Список, ПараметрыОтбора);
КонецПроцедуры 
```

### Дополнительные материалы

- [Структура модуля](https://its.1c.ru/db/v8std#content:455:hdoc)

**Comment by iArtemv** [comment]
возьму проверку
