### ISSUE TITLE
Стандарт 467: В качестве правого операнда операции сравнения "ПОДОБНО" указано поле таблицы.

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#86]
### Название проверки
`В качестве правого операнда операции сравнения "ПОДОБНО" указано поле таблицы.`

**Английское название проверки**
`??`

### Правило анализа кода/метаданных

1.2. Конфигурация должна быть одинаково рассчитана на работу со всеми
СУБД, операционными системами, веб-браузерами и различными режимами
работы, которые поддерживает платформа 1С:Предприятие.

Соблюдение стандартов "Приложение 8. Особенности работы с различными
СУБД"  
<http://its.1c.ru/db/v83doc#bookmark:dev:TI000001285>

8.3. Сервер IBM DB2
-------------------

● Правым операндом операции сравнения ПОДОБНО (LIKE) может быть только
литерал (параметр) или выражение над литералами. Шаблонными символами
являются только «\_» – любой символ и «%» – последовательность любых
символов.

Запрещено использовать в запросе поле таблицы (реквизит справочника) в
качестве правого операнда операции сравнения "ПОДОБНО", например:

... ПОДОБНО Таблица1.Поле1

### Мета-информация (пожалуйста, заполните если знаете):
- Номер стандарта: `467`
- Код проверки: `??my-check-id`
- Тип ошибки: `ERROR` `SECURITY` `PERFORMANCE`  `WARNING` `PORTABILITY` `LIBRARY_DEVELOPMENT_AND_USAGE` `CODE_STYLE` `UI_STYLE` `SPELLING`
- Критичность: `BLOCKER` `CRITICAL` `MAJOR` `MINOR` `TRIVIAL`
- Код ошибки АПК: `379`

#### Параметры проверки
- NA

#### Текст ошибки
`В качестве правого операнда операции сравнения "ПОДОБНО" указано поле таблицы.`

#### Пример некорректного решения
- NA

#### Пример корректного решения
- NA

#### Дополнительные материалы

- [Общие требования к конфигурации](https://its.1c.ru/db/v8std#content:467:hdoc)

**Comment by disant1** [comment]
Взял в работу.
