### ISSUE TITLE
Добавить некий префикс code style или другой символ для всплывающих сообщений

### ISSUE THREAD

**Issue by Desar14** [1C-Company/v8-code-style#862]
## Описание проблемы

Когда всплывают сообщения об ошибках - не всегда понятно, от чего данная ошибка. 

## Дополнительная информация
Например, на этом скриншоте - не понятно, от чего данная ошибка

![image](https://user-images.githubusercontent.com/66671103/139677860-e14e2a7e-f666-48a0-92d3-efc3d049be6c.png)

**Comment by marmyshev** [comment]
А можешь пояснить зачем это нужно? Т.е. когда видишь ошибку и читаешь текст. Что даст код/префикс?

Для "расследования" чья проверка - есть способ стандартный: открываешь ошибку в панели ошибок- ПКМ - открыть настройки проверки - там, код проверки, параметры и вся инфа чья проверка...

**Comment by marmyshev** [comment]
@Desar14  я правильно понимаю, что на мой вопрос:

> А можешь пояснить зачем это нужно? Т.е. когда видишь ошибку и читаешь текст. Что даст код/префикс?

Ответа четкого нет, верно? Есть ошибки и пожелания ЕДТ (см. ниже) - которые нужно зарегистрировать и исходная проблема будет решаться правильно. Эту задачу с префиксами закрываем?

> В данном случае ошибка вообще не попала в панель ошибок

Это ошибка ЕДТ - нужно завести багу в багтрекер по ЕДТ, если есть способ воспроизведения.
Имхо, не правильно из-за ошибки и вместо её исправления делать ухудшение читаемости текста ошибки какими-либо техногенными префиксами, а задачу поиска в панели - это никак не решает, а наоборот - нужно будет в строке поиска вводить по мимо текста ошибки -  еще и этот префикс.

> Или возможность из этого окошка попасть в панель ошибок с фокусом на этой ошибке, ибо когда ошибок много - сложно искать просто в списке.

Это пожелание - тоже в проект по ЕДТ, т.к. оно не относится к конкретной проверке или конкретному плагину с проверками. Очень хорошее пожелание (имхо)! Заведешь?

**Comment by Desar14** [comment]
Да, в целом всё, получается, нужно в едт складывать.
Этот плагин сам по себе вскрывает много ошибок/недоработок в самом ЕДТ, конечно :)
