### ISSUE TITLE
Ломаются проверки по всему модулю

### ISSUE THREAD

**Issue by Desar14** [1C-Company/v8-code-style#877]
### Описание ошибки

Много некорректных ошибок появляется в модуле, а в логе очень много Language check thrown an exception:false
Например,
![image](https://user-images.githubusercontent.com/66671103/143020559-0bba9a1d-a54e-4740-a06b-7f0735aeb058.png)
Хотя данный элемент есть в форме. Чинится любым редактированием в процедуре. И так нужно пройти каждую процедуру.

### Как воспроизвести

Стопроцентного воспроизведения нет, но в целом часто модуль формы внезапно ломается. В моём случае это произошло после переименования реквизита формы.

### Скриншоты

![image](https://user-images.githubusercontent.com/66671103/143020812-02a2b335-542f-45f4-b41d-b7349ee1cbad.png)

### Ожидаемое поведение

Модуль не должен ломаться

### Лог рабочей области

[trace.log](https://github.com/1C-Company/v8-code-style/files/7587771/trace.log)
[log.log](https://github.com/1C-Company/v8-code-style/files/7587772/log.log)

### Версия 1С:Code style V8

0.1.0.145

### Версия 1С:EDT

2021.2.8.3

### Операционная система

Windows

**Comment by marmyshev** [comment]
@Desar14 может быть модуль весь разломан в этот момент? Вот судя по логу ошибки - там вообще не может быть такого падения (ну т.е. это вообще какая-то дичь с модулем случилась, похоже).

**Comment by Desar14** [comment]
Слишком часто модуль приходит в такое состояние при каких-то простых изменениях. 
В данном случае, модуль был нормальный, затем после переименования реквизита формы - произошла вся эта дичь.

**Comment by marmyshev** [comment]
@Desar14 можешь проверить, на 2021.3 всё еще поведение сохраняется?

**Comment by Desar14** [comment]
Пока что не сталкивался, хотя не так активно сейчас пользую 2021.3.
