### ISSUE TITLE
Проверка variable-value-type не видит тип возвращаемого значения из другого контекста

### ISSUE THREAD

**Issue by Desar14** [1C-Company/v8-code-style#878]
### Описание ошибки

В модуле формы срабатывает ошибка variable-value-type на результат серверной функции в клиентской. 
![image](https://user-images.githubusercontent.com/66671103/144817251-d371a1a1-9a8e-4f62-a18b-6088a74fd541.png)
При этом сама ЕДТ понимает, что у переменной есть тип.
![image](https://user-images.githubusercontent.com/66671103/144817349-09118502-e665-4eaa-b145-793bc5a1a6d9.png)

Возможна проблема проявляется когда появляется описание у функции

### Как воспроизвести

Создать в модуле формы серверную функцию и получить из нее результат в клиентскую.

[ТестОшибкиЕДТ.zip](https://github.com/1C-Company/v8-code-style/files/7659449/default.zip)

### Ожидаемое поведение

Плагин видит тип возвращаемого значения и не ругается на него.

### Лог рабочей области

[trace.log](https://github.com/1C-Company/v8-code-style/files/7659469/trace.log)
[log.log](https://github.com/1C-Company/v8-code-style/files/7659472/log.log)

### Версия 1С:Code style V8

0.1.0.146

### Версия 1С:EDT

2021.2.10

### Операционная система

Windows

### Дополнительная информация

включены строгие типы

**Comment by korn-1c-ru** [comment]
Не срабатывает указание типа в строке 64, хотя, тоже самое в строке 60 срабатывает.
![image](https://user-images.githubusercontent.com/48685931/149710927-eceaaedd-0ac7-4a66-826e-9a935f6e1b4d.png)
