### ISSUE TITLE
Ложное срабатывание проверки "Цикл содержит метод вызова с запросом" в переменной цикла-коллекции

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/v8-code-style#905]
### Описание ошибки

В данном фрагменте функция ПолучитьНабор() вычисляется 1 раз и ошибки быть не должно.

![image](https://user-images.githubusercontent.com/54451084/147868568-bd3dbfa4-1ffc-4477-bc83-85926b6ae7a4.png)

### Как воспроизвести

1. Набрать код ниже

```
Процедура тест()
	
	Для Каждого Номер Из ПолучитьНабор() Цикл

	КонецЦикла;
	
КонецПроцедуры

Функция ПолучитьНабор()
	
	Запрос = Новый Запрос;
	Запрос.Текст = "ВЫБРАТЬ
	|	1 КАК Номер
	|
	|ОБЪЕДИНИТЬ ВСЕ
	|
	|Выбрать
	|	2
	|
	|ОБЪЕДИНИТЬ ВСЕ
	|
	|Выбрать
	|	3";
	
	Возврат Запрос.Выполнить().Выгрузить().ВыгрузитьКолонку("Номер");
	
КонецФункции
```
2. Второй вариант: загрузить проект из архива

[EDT-test.zip](https://github.com/1C-Company/v8-code-style/files/7798688/EDT-test.zip)

### Ожидаемое поведение

Ошибка в данном случае не должна возникать

### Лог рабочей области

[лог.zip](https://github.com/1C-Company/v8-code-style/files/7798689/default.zip)

### Версия 1С:Code style V8

0.2.0.114

### Версия 1С:EDT

Ruby 2021.3.0

### Операционная система

Windows

**Comment by marmyshev** [comment]
@DoublesunRUS вроде в чате обсудили что ошибка...

**Comment by DoublesunRUS** [comment]
Да, поправлю в выходные.
