### ISSUE TITLE
Стандарт 469: Клиентский глобальный модуль: ошибочное предупреждение о некорректном типе

### ISSUE THREAD

**Issue by ilya2184** [1C-Company/v8-code-style#924]
### Название проверки

Общий модуль имеет некорректный тип
common-module-type

EDT версия: Ruby 2021.3.0
1С:Стандарты разработки V8 версия: 0.2.0.114

### Правило анализа кода/метаданных

Не понятно как создать клиентский глобальный модуль:
По стандарту два флажка: Клиент (обычное приложение) и Клиент (управляемое приложение)

В результате получаем блокирующее предупреждение.
(+ в тексте предупреждения опечатка: некорректне)

- Номер стандарта: 469
- Код проверки: common-module-type
- Тип ошибки: CODE_STYLE
- Критичность: BLOCKER
- Код ошибки АПК:

### Параметры проверки

Настройка проверки не требуется

### Текст ошибки

Общий модуль для типа "Клиентский глобальный модуль" имеет некорректне настройки: Внешнее соединение, Клиент (управляемое приложение), Сервер

### Пример некорректного решения

Общий модуль с флагами: Глобальный, Клиент (управляемое приложение), Клиент (обычное приложение)
Остальные флаги - сняты, повторное использование = Не использовать

### Описание, почему так делать нельзя

Понятно что клиентские глобальные модули не очень-то хороший путь, но пока без них никак.

### Пример корректного решения

см. АПК
проверка Проверка общих модулей на совмещение клиент/сервер
ошибка Общий модуль недопустимого типа

### Дополнительные материалы

- https://its.1c.ru/db/v8std#content:469:hdoc
![За что предупреждение](https://user-images.githubusercontent.com/14931660/149654956-8144a536-34cf-4178-9613-28f4d319bd37.PNG)

**Comment by RedMammoth** [comment]
Также недозаполнено описание проверки: нет ссылки на стандарт и примеров:
![image](https://user-images.githubusercontent.com/64589646/149655320-2c829884-ba24-4710-8be1-6b4fc7ccad8f.png)

**Comment by marmyshev** [comment]
кажется ошибка тут в настройке типов модулей https://github.com/1C-Company/v8-code-style/blob/master/bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/CommonModuleTypes.java#L104
