### ISSUE TITLE
Добавить проверку Общая форма не используется.

### ISSUE THREAD

**Issue by DmitryShvaika** [1C-Company/v8-code-style#947]
### Описание проблемы

Хорошо было бы видеть неиспользуемые общие формы. Тем более, что проверить их использование достаточно просто.

### Описание решения проблемы

Если нет вызовов через ОткрытьФорму, ПолучитьФорму и форма не входит в состав ни одного командного интерфейса, то можно считать, что она не используется.

**Comment by RedMammoth** [comment]
а если я хитрым образом получил имя общей формы, как быть?

```bsl
ОткрытьФорму(ХитраяФункцияВозвращающаяИмяВЗависимовтиОтЧегото(Чтото));
```

**Comment by marmyshev** [comment]
В общем-то проверка будет очень тяжелая - нужно по каждой из сотен форм в конфигурации сделать скан всей конфигурации - всего кода...

Нужно проектировать систему как-то так чтобы работало быстро...

**Comment by DmitryShvaika** [comment]
Ну давайте пока не будем делать.... действительно однозначно не определить что форма не используется...
