### ISSUE TITLE
strict-types: Добавление типизированного значения в не типизированную коллекцию (Проверка)

### ISSUE THREAD

**Issue by sfaqer** [1C-Company/v8-code-style#954]
### Описание проблемы

Для реализации квик фикса описанного в #953 нужна проверка, которая проверяет что в не типизированную коллекцию добавляется типизированный элемент

### Описание решения проблемы

```bsl
	Результат = Новый Массив();
	
	Результат.Добавить(1); // Предупреждение: Добавление типизированного элемента в не типизированную коллекцию
```

Ну и исправление описанное в #953

**Comment by muhtimur** [comment]
Возьму задачу
