### ISSUE TITLE
Ошибка изменения типа значения

### ISSUE THREAD

**Issue by DitriXNew** [1C-Company/v8-code-style#963]
### Описание ошибки

Подозреваю что дубль #878
Но такая же ошибка высвечивается если я присваиваю результат функции элементы формы, или однозначно определяемым типам EDT

### Как воспроизвести

```bsl
// @strict-types

&AtClient
Procedure OnOpen(Cancel)
	Cancel = Test();
EndProcedure

&AtServer
Function Test()
	Return True;
EndFunction
```

### Скриншоты

![изображение](https://user-images.githubusercontent.com/11927866/153644930-62f55ea6-8cca-4d09-872e-ebcdd0ccdfb6.png)

### Ожидаемое поведение

-

### Лог рабочей области

-

### Версия 1С:Code style V8

0.2.0.114

### Версия 1С:EDT

2021.3.0

### Операционная система

Windows

**Comment by marmyshev** [comment]
@DitriXNew  На 2021.3.1 не воспроизводится.

Попробуй на 2021.3, если опять стабильно воспроизводится - приложи демо-кофну (может в каких-то прям свойствах проекта, версиях И так далее дело) и открывай Тикет.

**Comment by marmyshev** [comment]
Удалось воспроизвести.
