### ISSUE TITLE
Ложное срабатывание проверки: invocation-parameter-type-intersect - для методов с несколькими вариантами вызова

### ISSUE THREAD

**Issue by RedMammoth** [1C-Company/v8-code-style#992]
## Название/код проверки

Код проверки: `invocation-parameter-type-intersect`

Версия плагина: `0.2.0.159`

## Пример кода/метаданных содержащих ошибку

Возможно ошибка не в проверке, а в ЕДТ и проверка просто ее вскрыла

```bsl
// @strict-types

// Тест.
// 
// Параметры:
//  СправочникСсылка - СправочникСсылка.Справочник - Справочник ссылка
// 
// Возвращаемое значение:
//  Строка - Тест
Функция Тест(СправочникСсылка) Экспорт
	Возврат ПолучитьНавигационнуюСсылку(СправочникСсылка);
КонецФункции
```

![image](https://user-images.githubusercontent.com/64589646/154477223-3b2ad88e-ebe1-4fbd-82b9-09a5821de254.png)

## Почему это НЕ ошибка

Согласно СП есть вариант функции ПолучитьНавигационнуюСсылку с один параметром - ЛюбаяСсылка

**Comment by marmyshev** [comment]
С проверкой всё в порядке - она проверяет то, что ей предоставляют.

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/4069973/154576727-4fd979fa-2bcc-4715-8594-09e6c9c8e913.png">

Надо дальше разбираться почему выдается из нескольких вариантов вызова - только этот тип.

**Comment by RedMammoth** [comment]
Вот еще один пример нашел, когда выдается только один вариант вызова:
```bsl
Процедура Тест()

	// Метод Скопировать у ТаблицыЗначений подобрался корректно
	МояТаблица = Новый ТаблицаЗначений;
	МояТаблица.Колонки.Добавить("НомерСтроки", Новый ОписаниеТипов("Число"));
	МояТаблица.Колонки.Добавить("ПометкаУдаления", Новый ОписаниеТипов("Булево"));
	МояТаблица.Колонки.Добавить("СсылкаНаСправочник", Новый ОписаниеТипов("СправочникСсылка.Справочник"));

	СтруктураПоиска = Новый Структура;
	СтруктураПоиска.Вставить("ПометкаУдаления", Истина);

	СтрокиКОбработке = МояТаблица.Скопировать(СтруктураПоиска, "НомерСтроки, СсылкаНаСправочник");
	Для Каждого СтрокаТЗ Из СтрокиКОбработке Цикл

	КонецЦикла;
	
	// А вот метод Выгрузить у ТабличнойЧасти - нет
	// метод ожидает всегда массив
	НовыйСправочник = Справочники.Справочник.СоздатьЭлемент();
	СтрокиТЧ = НовыйСправочник.ТабличнаяЧасть.Выгрузить(СтруктураПоиска, "НомерСтроки, СсылкаНаСправочник");
	Для Каждого СтрокаТЧ Из СтрокиТЧ Цикл

	КонецЦикла;

КонецПроцедуры
```

**Comment by Nspection** [comment]
![image](https://user-images.githubusercontent.com/98949112/157643081-99ea2021-32b1-44ea-b138-a196329b4351.png)
похожая ошибка
