### ISSUE TITLE
Добавить квик-фикс конвертации функции в процедуру

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/v8-code-style#995]
### Описание проблемы

Например есть проверка `function-return-types `- находит проблему что у функции нет типа, при этом если нет возврата - действием по исправлению - может быть как добавление возврата так и переделка функции в процедуру.

```bsl
&НаКлиенте
Функция СсылкаНаЭлементСпискаПоШтрихкоду(Штрихкод)
	
	ШтрихкодированиеПечатныхФормВызовСервера.СсылкаНаЭлементСпискаПоШтрихкоду(
		Штрихкод, ХозяйственныеОперацииИДокументы.Выгрузить());
	
КонецФункции
```

### Описание решения проблемы

Можно сделать квик-фикс по переделке функции в процедуру

### Дополнительная информация

К каким еще проверкам привязать такой квик-фикс?

**Comment by MuhTimur** [comment]
Я возьму для начала ее. (Команда Xored)

**Comment by muhtimur** [comment]
Возьму задачку
