### ISSUE TITLE
Ложное срабатывание проверки: invocation-parameter-type-intersect для Списка значений

### ISSUE THREAD

**Issue by jsteugene** [1C-Company/v8-code-style#997]
## Название/код проверки

Код проверки: `invocation-parameter-type-intersect`

Версия плагина: `0.2.0.159`

## Пример кода/метаданных содержащих ошибку

```bsl
// @strict-types

Процедура ВоспроизведениеОшибки()

	Переменная = "Текст";
	
	СписокЗначений = Новый СписокЗначений();
	СписокЗначений.Добавить(Переменная);

КонецПроцедуры
```

![image](https://user-images.githubusercontent.com/66112045/154951843-778a67a2-e777-4033-be66-136a066d2cc1.png)

## Почему это НЕ ошибка

Метод СписокЗначений.Добавить() ожидает в качестве первого параметра произвольный тип.

![image](https://user-images.githubusercontent.com/66112045/154952112-f6f4e281-db07-4422-ba50-321268a631fb.png)

## Дополнительные материалы

Вот так ошибку не выдает:

```bsl
// @strict-types

Процедура ВоспроизведениеОшибки()

	Переменная = "Текст";
	
	СписокЗначений = Новый СписокЗначений();
	ЭлементСписка = СписокЗначений.Добавить();
	ЭлементСписка.Значение = Переменная;

КонецПроцедуры
```
![image](https://user-images.githubusercontent.com/66112045/154952857-3bc09919-d6b1-4e3a-90af-423f2557e29e.png)

**Comment by marmyshev** [comment]
Да подтверждаю, ошибка.

У типа "СписокЗначений" ситуация аналогичная как и у типа "Соответствие" - нужно делать кастомную логику вычисления типа значения.
